### ISSUE TITLE
 PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownErrorException: unknown error: cannot determine loading status from unknown error: missing or invalid columnNumber

### ISSUE THREAD

**Issue by QuestionDevelopment** [php-webdriver/php-webdriver#1011]
### Bug description

When attempting to run 

`$this->driver->get($url);`

the following error gets produced

```
 "POST / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "example.url.com"
2022/09/09 08:16:22 [error] 165727#165727: *1967 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownErrorException: unknown error: cannot determine loading status
from unknown error: missing or invalid columnNumber
  (Session info: headless chrome=104.0.5112.101) in /var/www/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
Stack trace:
#0 /var/www/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(372): Facebook\WebDriver\Exception\WebDriverException::throwException()
#1 /var/www/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(585): Facebook\WebDriver\Remote\HttpCommandExecutor->execute()
#2 /var/www/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(246): Facebook\WebDriver\Remote\RemoteWebDriver->execute()
#3 /var/www/vendor/symfony/panther/src/Client.php(529): Facebook\WebDriver\Remote\RemoteWebDriver->get()
#4 /var/www/project/example.php(25): Symfony\Component\Panther\Client->get()
#5 /var/www/api.php(128): project\example->example()
#6 /var/www/ap" while reading response header from upstream, client: 45.45.45.45, server: example.url.com, request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "example.url.com"

```
### How could the issue be reproduced

I am very unclear what is going on so I apologize I can not give you an exact method to reproduce.   The code works perfectly when run from a browser.  However, when I run the same code, url and parameters being passed via curl the error occurs.

### Code : Initialization of driver

```
    public function driver()
    {
        require_once $this->directory . 'vendor/autoload.php';
        return \Symfony\Component\Panther\Client::createChromeClient('/var/www/drivers/chromedriver');
    }
```

### Code : What produces error

```
$this->driver->get($url);
```

Removing this line allows script to run perfectly.

### Expected behavior

The code to run without error above.

### Details

* Php-webdriver version: 1.12.1
* PHP version:  PHP 8.1.9 
* How do you start the browser driver or Selenium server: [Panther](https://github.com/symfony/panther)
* Selenium server version: Not used
* Chromedriver version: 104.0.5112.79
* Browser used + version:  CURL
* Operating system: Debian 11

### Additional context
Here is the data I could collect from curl request 

```
URL : https://example.url.com
HTTP Code : 500
Error : 0
Type : POST
Response Headers : Array(    [server] = nginx1.18.0    [date] = Fri, 09 Sep 2022 11:58:06 GMT    [content-type] = texthtml charset=UTF-8    [transfer-encoding] = chunked    [connection] = keep-alive)User Agent : Mozilla5.0 (Windows NT 10.0 Win64 x64) AppleWebKit537.36 (KHTML, like Gecko) Chrome104.0.0.0 Safari537.36Request Headers :nArray(    [0] = Content-type: applicationx-www-form-urlencoded)Content : url=example.url.com/?with=params

Curl Info : Array(    [url] = https://example.url.com    [content_type] = texthtml charset=UTF-8    [http_code] = 500    [header_size] = 189    [request_size] = 548    [filetime] = -1    [ssl_verify_result] = 0    [redirect_count] = 0    [total_time] = 12.646657    [namelookup_time] = 0.058508    [connect_time] = 0.064617    [pretransfer_time] = 0.111254    [size_upload] = 282    [size_download] = 0    [speed_download] = 0    [speed_upload] = 22    [download_content_length] = -1    [upload_content_length] = 282    [starttransfer_time] = 12.646189    [redirect_time] = 0    [redirect_url] =     [primary_ip] = webdrive_ip    [certinfo] = Array        (        )    [primary_port] = 443    [local_ip] = source_server_ip    [local_port] = 53264    [http_version] = 2    [protocol] = 2    [ssl_verifyresult] = 0    [scheme] = HTTPS    [appconnect_time_us] = 110749    [connect_time_us] = 64617    [namelookup_time_us] = 58508    [pretransfer_time_us] = 111254    [redirect_time_us] = 0    [starttransfer_time_us] = 12646189    [total_time_us] = 12646657)
```

I would appreciate any help you could provide

**Comment by QuestionDevelopment** [comment]
The scenario in which the error occurs is as follows.  Website makes API call to local script.  Server side of website makes curl request to external "Panther/php-web driver" api endpoint.  Direct connection to api endpoint via browser works perfectly.  Curl request fails.  

I put an hour in trying to get the logging to work.  I was unable.   Please let me know if it is required.

**Comment by OndraM** [comment]
Hi, I'm still confused about the scenario and I don't understand what and why are you trying to achieve, I'm sorry.

Why and how exactly do you use CURL? Php-webdriver is usually run on one machine (your computer, your build server etc.), and calls remote end (the browser driver, like chromedriver) endpoints. The browser (which is running either on your machine or on some remote IP) then executes the received commands in the browser. I don't understand how could CURL be part of this scenario. There is CURL involved inside php-webdriver, but I guess you are not talking about this, or are you?

Could you somehow describe the exact steps how to reproduce the issue and provide the code/commands you execute? You must be doing something quite unusual, which may be the reason why you get the errors.

**Comment by QuestionDevelopment** [comment]
Thank you for your patience.  Let me try to explain in a clear way what I am doing.

Situation 1 : Directly connecting to API endpoint = Which works properly.  

`Goto url with browser : https://panther.example.com/?project=projectName&script=article&key=projectKey&url=https%3A%2F%2Fapi-platform.com`

Situation 2 : Using API endpoint from server = Does not work

Visit website ie. https://www.sample.com.  Click a button.  This triggers an ajax call to the https://www.sample.com server.  The https://www.sample.com server then connects to the above (situation 1) API endpoint via CURL passing all the same information.  This produces the error that I provided.

**Comment by QuestionDevelopment** [comment]
@OndraM 

So I've put 20+ hours into this and I think it is actually to do with the website I am trying to receive.  Can you test if this produces the error please?  I don't know how long the page will be up for unfortunately.

```
$url = 'https://www.cnn.com/2022/09/15/politics/biden-white-house-railroad-strike/index.html';
$this->driver->get($url);
```

**Comment by QuestionDevelopment** [comment]
Thank you for all your time/help.  I am going to close this ticket until I determine exactly what is going on.
