### ISSUE TITLE
isDisplayed(): element is not attached to the page

### ISSUE THREAD

**Issue by AndreKR** [php-webdriver/php-webdriver#1019]
### Bug description
I have a page that is rendered by Vue.js which contains a loading spinner `<div class=".bg-spinner">`.

In my test case I want to wait for the loading spinner to disappear, for this I'm using:
```php
$this->driver->wait()->until(function () {
	return !$this->driver->findElement(WebDriverBy::cssSelector('.spinner-bg'))->isDisplayed();
});
```

Sometimes I get an exception from `isDisplayed()`:

```
Facebook\WebDriver\Exception\StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: headless chrome=94.0.4606.61)
```

Stacktrace:
```
/app/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:127
/app/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:371
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:591
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php:27
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebElement.php:310
```

My guess is that Vue removed the element between `findElement()` and `isDisplayed()`.

Should `isDisplayed()` maybe return false in this case? I'm not sure what the policy is for such error handling. Otherwise `isDisplayed()` pretty much always has to be wrapped in `try/catch` I guess?

Or perhaps a more explicit approach would be to provide a convenience function `tryIsDisplayed()`.

### Details

* Php-webdriver version: 1.11.1
* PHP version:  7.4.26-r0
* How do you start the browser driver or Selenium server: https://hub.docker.com/r/blueimp/chromedriver
* Browser driver version: Chromedriver 93.0.4577.63
* Browser used + version: https://hub.docker.com/r/blueimp/chromedriver
* Operating system: Docker on Ubuntu

**Comment by OndraM** [comment]
Hi, 
for this usecase, I'd recommend using visibilityOfElementLocated().

This wait condition takes care of the StaleElementException.

See https://github.com/php-webdriver/php-webdriver/wiki/HowTo-Wait#elements-visibility-and-invisibility

**Comment by AndreKR** [comment]
Those examples are missing the `return`, aren't they?
