### ISSUE TITLE
sendKeys fail silently in iframe

### ISSUE THREAD

**Issue by olleharstedt** [php-webdriver/php-webdriver#1037]
### Bug description

The following code fails silently for us:

```php
self::$webDriver->switchTo()->frame($iframe);
$body = self::$webDriver->findElement(WebDriverBy::tagName('body'));
sleep(2);
$body->clear()->sendKeys($text);
```

$iframe is not empty, if it was there would have been an error earlier. Same logic for $body. This one used to work but started to fail on github actions after we upgraded to a later Ubuntu version. I can reproduce the error locally tho.

Updating to latest webdriver version did not fix it.

### How could the issue be reproduced

Hard, but see our CI here: https://github.com/LimeSurvey/LimeSurvey/actions/runs/3685706349/jobs/6236995409

You'd have to set it up locally to reproduce, or try to create a more minimal example using iframe and ckeditor perhaps.

### Expected behavior

At least silently fail. :)

### Php-webdriver version

1.13

### PHP version

8.0

### How do you start the browser driver or Selenium server

Java jar

### Selenium server / Selenium Docker image version

selenium-server-standalone-3.7.1.jar

Updating to selenium-server-standalone-3.141.59.jar did not fix it.

### Browser driver (chromedriver/geckodriver...) version

geckodriver-v0.32.0-linux64.tar

### Browser name and version

Firefox

### Operating system

Ubuntu 20.04

### Additional context

Let me know if you need more info. Our code is open-source, you can find the failing code here: https://github.com/LimeSurvey/LimeSurvey/blob/master/tests/functional/backend/QuestionGroupEditorTest.php#L236

**Comment by olleharstedt** [comment]
The following solution works for me:

```php
$body->click();
$body->clear();
$body->click();
$body->sendKeys($text);
```
Not sure why needed.

**Comment by OndraM** [comment]
Hi @olleharstedt , are you able to test it in different browser than Firefox / Geckodriver and see if it behaves the same or not?

And if you run the test locally, do you observe some difference when using your workaround? For example - does the viewport get scrolled to the iframe before the text is entered or not? There are various reported bugs in Geckodriver mentioning something similar (iframe don't get scrolled into view and the send text / click is ignored), eg. https://github.com/mozilla/geckodriver/issues/651 , so it could be related.

**Comment by olleharstedt** [comment]
We're only using FF in our CI, and I don't really have the time to dig deeper since it's "fixed", sorry. What I could see, the iframe _was_ scrolled into view.

Thanks for the tip about geckodriver!
