### ISSUE TITLE
Unexpected server response to findElement command

### ISSUE THREAD

**Issue by ppodgorskicrido** [php-webdriver/php-webdriver#1047]
### Bug description

I try to get all text from page. It is printed but then the exception: `Facebook\WebDriver\Exception\UnknownErrorException` is thrown.
The same error was both on chrome and firefox. I presume that is connected to #657

### How could the issue be reproduced

```shell
$this->driver = RemoteWebDriver::create($serverUrl, DesiredCapabilities::firefox());
$this->driver->get($url);
$text = $this->driver->findElement(WebDriverBy::tagName('body'))->getText();
$this->driver->quit();
```

### Php-webdriver version

1.13.1

### PHP version

8.1.5

### How do you start the browser driver or Selenium server

driver

### Operating system

Win 11

**Comment by OndraM** [comment]
Hi, could you please provide the full exception message you get?

Also, is it possible to provide error log from chromedriver/geckodriver?

**Comment by OndraM** [comment]
Also, we do have some changes related to this in not-yet released version. Could you try this issue with main branch of php-webdriver?

**Comment by ppodgorskicrido** [comment]
Unfortunately, this the full message: `Unexpected server response to findElement command`. There are no drivers messages.

I tried with dev-main branch. It is working now!

**Comment by OndraM** [comment]
> I tried with dev-main branch. It is working now!

Great, I'm planning to release the new version today! So closing this, thanks for confirmation.

**Comment by OndraM** [comment]
Ok, so try this in new version 1.14.0.

**Comment by ppodgorskicrido** [comment]
It's working. Thank you!
