### ISSUE TITLE
String replace gets null as parameter

### ISSUE THREAD

**Issue by art0s-dev** [php-webdriver/php-webdriver#1052]
### Bug description

Hello There,

This is the error message:
Whoops\Exception\ErrorException : str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated
[...]/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:271

` $url = str_replace(':sessionId', $command->getSessionID(), $url);`

The get session ID method is returning null. 
Muting the Error works so far, but it's only a temporary solution.
Haven't looked deeper in the Package.

Cheers.

### How could the issue be reproduced

```shell
SETUP:
- Java standalone server on docker-compose
- PestPHP as testing framework

<?php declare(strict_types=1);

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;

beforeEach(function () {

    /error_reporting(E_ERROR);
    ini_set('display_errors', '1');

    $this->webdriver = RemoteWebDriver::create( 'http://localhost:4444/', DesiredCapabilities::chrome());
});

test("User can see the hello world message", function () {
    $this->webdriver->get('http://localhost:80');
    $text = $this->webdriver->findElement(WebDriverBy::tagName('body'))->getText();
    $this->assertEquals('hello there!',$text);
});
```

### Expected behavior

Webdriver finds the text

### Php-webdriver version

1.1.3

### PHP version

8.1

### How do you start the browser driver or Selenium server

Selenium server jar on Docker compose

### Selenium server / Selenium Docker image version

4.8.0

### Operating system

Ubuntu 22.10

**Comment by OndraM** [comment]
Hi, could you try with the latest php-webdriver version (1.14.0)?

**Comment by art0s-dev** [comment]
Yup, upgraded to 1.14 and ran into the next one 

Facebook\WebDriver\Exception\SessionNotCreatedException : Could not start a new session. Error while creating session with the driver service. Stopping driver service: Driver server process died prematurely.
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-60-generic', java.version: '11.0.18'
Driver info: driver.version: unknown 
Host info: host: '2ccb55508337', ip: -----
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-60-generic', java.version: '11.0.18'
Driver info: driver.version: unknown

**Comment by OndraM** [comment]
This seems like and unrelated issue - probably incompatible version of Chrome and Chromedriver.

Please, try with the latest version of chromedriver, chrome and php-webdriver.
