### ISSUE TITLE
Adding --start-maximized to ChromeOptions does not maximize the browser when launching inside latest docker containers

### ISSUE THREAD

**Issue by jamesmortensen** [php-webdriver/php-webdriver#1061]
### Bug description

When using older docker-selenium's  selenium/standalone-chrome:106.0, we can start a session and open Chrome fully maximized.  But as of the latest version, this option seems to be ignored, but only for the PHP language bindings.  I've confirmed the option is processed for both the Selenium JavaScript and Python language bindings.  

The option is processed for the local Chrome browser. It only seems to be a problem when connecting to Selenium servers and browsers inside docker containers.

I also took the 106.0 tagged image and upgraded the Selenium server from 4.5.3 to 4.8.1 and replicated the same issue.  It seems something changed in Selenium, but it only seems to affect the PHP language bindings.

I dockerized the PHP test scripts since I don't normally run PHP.  You can clone a sample project and build the PHP container image:

```
$ git clone https://github.com/jamesmortensen/debug-tools-for-docker-selenium.git && cd debug-tools-for-docker-selenium
$ cd php-webdriver
$ docker build -t phpwebdriver .
$ docker run --rm -it phpwebdriver bash
```

Afterwards, start the two docker-selenium containers using the following commands.  If you run everything in the following order, then the local docker IP addresses should still match up as long as you aren't running any other containers at the time.

```
docker run --rm --shm-size 2g -p 4444:4444 -p 7900:7900 -p 5900:5900 -e SE_SCREEN_WIDTH=1920 -e SE_SCREEN_HEIGHT=1080 selenium/standalone-chrome:latest
```

```
docker run --rm --shm-size 2g -p 4445:4444 -p 7901:7900 -p 5901:5900 -e SE_SCREEN_WIDTH=1920 -e SE_SCREEN_HEIGHT=1080 selenium/standalone-chrome:106.0
```

In the phpwebdriver container, execute `php remote-demo.php` and observe the behavior in the container.  You'll need to edit the RemoteWebDriver::create line to swap out the URL with the container's IP address, such as 172.17.0.3 and so forth.

You'll see that, for 106.0 container, the browser is maximized, but not for the latest.

### How could the issue be reproduced

```shell
#!/usr/bin/env php
<?php
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Chrome\ChromeOptions;

# https://github.com/php-webdriver/php-webdriver/issues/537#issuecomment-1004396394
require_once('../vendor/autoload.php');

$host106 = "http://172.17.0.3:4444";
$host111 = "http://172.17.0.2:4444";
$hostLocal = "http://host.docker.internal:3100";

// Chrome
$options = new ChromeOptions();
$options->addArguments(['--start-maximized']);
$desiredCapabilities = DesiredCapabilities::chrome();

$desiredCapabilities->setCapability(ChromeOptions::CAPABILITY, $options);

$driver = RemoteWebDriver::create($hostLocal, $desiredCapabilities);
$driver->get("https://google.com");

sleep(10);

$driver->quit();

?>
```

### Expected behavior

Expecting the Chrome browser to maximize in the latest docker-selenium container when `--start-maximized` is present using the PHP language bindings.

### Php-webdriver version

1.14.0

### PHP version

7.4

### How do you start the browser driver or Selenium server

See above examples using docker run

### Selenium server / Selenium Docker image version

4.8.1

### Browser driver (chromedriver/geckodriver...) version

chromedriver 110.0.5481.77

### Browser name and version

Google Chrome 110.0.5481.77

### Operating system

Ubuntu 20.04 Intel GitPod and macOS 13.2.1 M2

### Additional context

This issue is confirmed on both docker-selenium and docker-seleniarm.  The behavior is the same and for only the PHP language bindings when running with docker.

**Comment by OndraM** [comment]
See #1063 for a fix. This will be part of release 1.14.1.

**Comment by jamesmortensen** [comment]
Thank you for the fix. I will pass the message to the docker-seleniarm community as well.
