### ISSUE TITLE
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownErrorException

### ISSUE THREAD

**Issue by AGenchev** [php-webdriver/php-webdriver#1073]
### Bug description

I get:
`PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownErrorException: Reached error page: about:neterror?e=dnsNotFound&u=http%3A//google.comasfasfasf/&c=UTF-8&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20google.comasfasfasf.`

when I test whether I can catch errors using non-existing domain.

### How could the issue be reproduced

```shell
a class method with the following code:
try
	  	{
			$this->webdriver->get('http://google.comasfasfasf'); // test non existing url
		}
catch(Exception $e) 
		{
	 		self::log('~75 exception: ' .  $e->getMessage(),9);
		}
```

### Expected behavior

the exception should be caught in the catch(Exception $e)  statement so the code could handle it.

### Php-webdriver version

1.14.0

### PHP version

PHP 7.4.3-4ubuntu2.19 (cli) (built: Jun 27 2023 15:49:59)

### How do you start the browser driver or Selenium server

started 'geckodriver' from a separate console

### Browser driver (chromedriver/geckodriver...) version

geckodriver 0.33.0

### Operating system

Ubuntu 20.04.6 LTS

### Additional context

To my understanding, trying non-existing URL should not be PHP fatal, because it is not error in the code. Also I think (but I might be wrong) that catch(Exception $e)  should be able to catch all exceptions which can then be checked for a given type. Update: I will check whether this is namespace problem.

**Comment by OndraM** [comment]
Hi, this does not seem as a php-webdriver issue: you most probably don't catch the right Exception, please check the namespace or you can explicitly try to catch `WebDriverException` to catch all exceptions thrown by  php-webdriver:

```php
try {
    //  ...
} catch (\Facebook\WebDriver\Exception\WebDriverException $e) {
    // ...
}
```

In case you think there is some php-webdriver issue, feel free to reopen this issue or create a new one.
