### ISSUE TITLE
Sample code and examples are still using Facebok

### ISSUE THREAD

**Issue by elnath78** [php-webdriver/php-webdriver#1093]
### Bug description

Please update the docs

### How could the issue be reproduced

```shell
//look at the docus, they all feature Facebook/*
```

### Php-webdriver version

1.15

### PHP version

8.1

### How do you start the browser driver or Selenium server

irrilevant

**Comment by OndraM** [comment]
Changing the namescape would be BC. So it could by done only in major version.
