### ISSUE TITLE
Headless Browser Selenium Remote Webdriver Php

### ISSUE THREAD

**Issue by rakeshbitling** [php-webdriver/php-webdriver#111]
Hello Friends,
                   I am working on selenium here I want to know that how selenium should work for php as headless.
This is my code snippets :
    $host = 'http://localhost:4444/wd/hub'; // this is the default
    $capabilities = array(WebDriverCapabilityType::BROWSER_NAME => '*firefox');
    $driver = RemoteWebDriver::create($host, $capabilities,1000);
    I dont want to open browser and close browser it should be done at background.
Please Help me its too much urgent for me
Env: OS centos
       Selenium ver 2.37 jar
       lang:Php

**Comment by brainm** [comment]
**alekciy** code in composer style:

```php
require_once __DIR__ . "/vendor/autoload.php";

use \Facebook\WebDriver\Remote\WebDriverCapabilityType;
use \Facebook\WebDriver\Remote\RemoteWebDriver;
use \Facebook\WebDriver\WebDriverDimension;

$host = '127.0.0.1:8910';
$capabilities = array(
    WebDriverCapabilityType::BROWSER_NAME => 'phantomjs',
    'phantomjs.page.settings.userAgent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0',
);
$driver = RemoteWebDriver::create($host, $capabilities, 5000);

$window = new WebDriverDimension(1024, 768);
$driver->manage()->window()->setSize($window);

$driver->get('https://www.google.ru/');

$driver->takeScreenshot('/tmp/screen.png');
$driver->quit();
```
