### ISSUE TITLE
Enhancement request: LocalFileDetector, or a way to send files to a remote server

### ISSUE THREAD

**Issue by linguinee** [php-webdriver/php-webdriver#115]
The [RemoteWebDriver](http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html) has a method `setFileDetector(FileDetector detector)`: "Set the file detector to be used when sending keyboard input." An example of how this works is in this [Selenium File Upload](http://saucelabs.com/resources/selenium-file-upload) example.

My use case is when I have files on a local machine, but they need to be on a remote server (node on Selenium grid) for a test to be executed. It would be awesome to have a way to send files through the JSON wire protocol. My request is for a way to do so - not necessarily using `setFileDetector()`, since that actually won't work for my purposes. I use Appium, so I need a way to send the compiled app to appropriate node in order for the test to even begin.

Addendum: There seems to be an [undocumented endpoint](http://t35822.web-selenium-development.htmltalk.us/undocumented-jsonwireprotocol-for-file-upload-t35822.html) on the server for uploading files? Someone also [mentioned it on StackOverflow](http://stackoverflow.com/questions/15280382/json-wire-protocol-sessionid-file-file-size-limit). File upload is implemented in the [Java bindings](https://groups.google.com/forum/#!topic/selenium-developers/kDSygyDfqD0), but not required. It would be great if it was implemented in the PHP bindings!

**Comment by acidjazz** [comment]
anyone who came here from Laravel Dusk

```php

      $file_input = $browser->driver->findElement(\Facebook\WebDriver\WebDriverBy::cssSelector('.input-image > input'));
      $file_input->setFileDetector(new \Facebook\WebDriver\Remote\LocalFileDetector());
      $file_input->sendKeys(__DIR__.'/images/logo.png');
```

**Comment by OndraM** [comment]
Or see page [Upload a file](https://github.com/facebook/php-webdriver/wiki/Upload-a-file) in our wiki ;-).
