### ISSUE TITLE
WebDriverSelect::selectByVisibleText issue

### ISSUE THREAD

**Issue by romulodl** [php-webdriver/php-webdriver#135]
I'm trying to select an option in a dropdown list using `WebDriverSelect::selectByVisibleText` on Firefox and I get the focus on the desired option, but when I do the next step the previous value still selected.

Am I doing something wrong?

**Comment by leogoesger** [comment]
I think you can just add a wait to solve this.

**Comment by OndraM** [comment]
For anyone thinking he is affected by this issue, please open a new issue (with all additional information - like browser version, code used etc.) Thanks for cooperation :)
