### ISSUE TITLE
Catchable fatal error: Object of class RemoteWebElement could not be converted to string in C:\path\file.php on line 130

### ISSUE THREAD

**Issue by billdev** [php-webdriver/php-webdriver#139]
`128  $els = $driver->findElements( WebDriverBy::className( 'nameofclass' ) );
129  foreach ( $els as $key => $el ) {
130  $txt = $el.getText('');
131  }`

The code above produces the error message:
Catchable fatal error: Object of class RemoteWebElement could not be converted to string in C:\path\file.php on line 129

I can work around the error by adding the following code to RemoteWebElement.php
`public function __toString() {
  return $this->getText();
}`

php-webdriver
selenium-server-standalone-2.41.0.jar
Windows 7 SP1
Firefox 28
xampp includes
Apache/2.4.7 (Win32) OpenSSL/1.0.1e PHP/5.5.9

**Comment by bmk10** [comment]
$buttonNext2	 =  $driver->findElement(WebDriverBy::tagName("body"));
	//array_push($URLSArray,$URLPARSE1); 
	
	
	
	
//echo  $googlemapsresult = $buttonNext2->getAttribute('innerHTML');

echo "buttonNext2->getAttribute('innerHTML";

 $googlemapsresult = $buttonNext2->getAttribute('innerHTML');

**Comment by gabrielpreston** [comment]
innerHTML is not a DOM element attribute, you'll need to use an executeScript() call to get what you need here.

**Comment by emiglobetrotting** [comment]
You can do this, for example 

	$ul = $driver->findElement(WebDriverBy::xpath('.//ul[@id="<put the id here>"]'));
        $lis = $ul->getAttribute('innerHTML');
