### ISSUE TITLE
Have a problem in composer update

### ISSUE THREAD

**Issue by duycanh** [php-webdriver/php-webdriver#180]
Hi, i have a problem with composer update, i am added facebook/webdriver to file composer.json

"require": {
    "php": ">=5.3.19",
    "facebook/webdriver": "0.5.1"
  },
  "require-dev": {
    "phpunit/phpunit": "3.7._",
    "phpdocumentor/phpdocumentor": "2._"
  },

or

"require": {
    "php": ">=5.3.19",
    "facebook/webdriver": "dev-master"
  },
  "require-dev": {
    "phpunit/phpunit": "3.7._",
    "phpdocumentor/phpdocumentor": "2._"
  },

When i run composer update in command line, it show error:

---

D:\Webserver\Apache2\htdocs\demo\php-webdriver-master>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package facebook/webdriver 1.0.0 could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
## Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Please help me, thanks

**Comment by Eddcapone** [comment]
Where is composer.js? Do you mean composer.json? And which is the line you are talking about? All lines?
