### ISSUE TITLE
UnhandledWebDriverError: Error forwarding the new session Error forwarding the request Read timed out

### ISSUE THREAD

**Issue by ghost** [php-webdriver/php-webdriver#32]
I've just upgraded my Selenium grid server and nodes to 2.21.0 (http://code.google.com/p/selenium/downloads/detail?name=selenium-server-standalone-2.21.0.jar&can=2&q=)

When a test is run, the browser opens, but the test fails immediately with an UnhandledWebDriverError:

`UnhandledWebDriverError: Error forwarding the new session Error forwarding the request Read timed out`

If I role the server and nodes back to selenium 2.15.0, the tests run fine.

2.21.0 has been out for a week or so now, and I can't find any similar problems; I'm going to head over to the Selenium bug tracker and log a bug there.

Has anybody here come across this?

Cheers,
Matt

**Comment by peterbollen** [comment]
Did you found a solution for this?
