### ISSUE TITLE
Uncaught exception 'Facebook\WebDriver\Exception\UnknownCommandException' with message 'POST /session/beac4f3b-367f-4531-9637-6f2aea8f1367/moveto did not match a known command

### ISSUE THREAD

**Issue by gohelkiran** [php-webdriver/php-webdriver#380]
I am getting below exception when doing draganddrop or moveByOffset events

Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownCommandException' with message 'POST /session/beac4f3b-367f-4531-9637-6f2aea8f1367/moveto did not match a known command Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700' System info: host: 'WIN-MT0KFAH3HJN', ip: '10.0.0.98', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_112' Driver info: org.openqa.selenium.firefox.FirefoxDriver Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], 

Below is my code
--------------------------------
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\Remote\DesiredCapabilities;

require 'vendor/autoload.php';

$host = 'http://localhost:4444/wd/hub';

$driver = RemoteWebDriver::create($host, DesiredCapabilities::firefox());
$driver->get('http://www.w3schools.com/html/html5_draganddrop.asp');

$drag = $driver->findElement(WebDriverBy::cssSelector('HTML>HEAD:first-child+BODY>DIV#belowtopnav>DIV:first-child>DIV#main>DIV#div1>IMG#drag1'));
$drop = $driver->findElement(WebDriverBy::cssSelector('HTML>HEAD:first-child+BODY>DIV#belowtopnav>DIV:first-child>DIV#main>DIV#div2'));

$driver->action()->clickAndHold($drag)->moveByOffset(500, 500)->perform();
$driver->close();

How can I perform dragAndDrop event?

**Comment by OndraM** [comment]
@gohelkiran Hi, what version of browser (Firefox?) do you use?

**Comment by gohelkiran** [comment]
it is Firefox 50.0
