### ISSUE TITLE
Update to latest PHPUnit

### ISSUE THREAD

**Issue by maortega** [php-webdriver/php-webdriver#500]
### What are you trying to achieve? (Expected behavior)
Make unit tests run on phpUnit version 6

### What do you get instead? (Actual behavior)
Class 'PHPUnit_Framework_TestCase' not found

### How could the issue be reproduced? (Steps to reproduce)
Try to run phpunit ./tests with phpunit version 6 installed

### Details
You will need to refactor things like \PHPUnit_Framework_TestCase to \PHPUnit\Framework\TestCase
Source: https://stackoverflow.com/questions/6065730/why-fatal-error-class-phpunit-framework-testcase-not-found-in

* Php-webdriver version: 
* PHP version: 7.1.8
* Selenium server version: 3.7.1
* Operating system: macOS High Sierra (10.13.1)
* Browser used + version:

**Comment by OndraM** [comment]
Hi, PHPUnit 6 is not supported right now.

Php-webdriver still keeps compatibility with PHP 5.x, which requires also PHPUnit 5.x. This will probably change in the near future (and some steps for PHPUnit 6 support were already done - see https://github.com/facebook/php-webdriver/pull/498 .

**Comment by driesvints** [comment]
Think this can be closed now? PHPUnit 9 is now added to the build here: https://github.com/php-webdriver/php-webdriver/pull/828

**Comment by williamdes** [comment]
Fixed by #828
