### ISSUE TITLE
[FEATURE REQUEST] Appium support

### ISSUE THREAD

**Issue by itaibh** [php-webdriver/php-webdriver#589]
### What are you trying to achieve? (Expected behavior)
A specific class for Appium tests (`AppiumDriver`, perhaps?)

### What do you get instead? (Actual behavior)
`RemoteWebDriver`, which seems to be the only `WebDriver` implementation.

**Comment by OndraM** [comment]
I think this is out of scope of php-webdriver.

Appium is Extending WebDriver protocol, so maybe Appium can implement extension of php-webdriver, which is built on top of `WebDriver` class? There is already [Appium PHP client](https://github.com/appium/php-client) provided by Appium project itself, however, it is not built on top of php-webdriver, but the outdated PHPUnit extension...

**Comment by williamdes** [comment]
@OndraM and could you clone it in your namespace or is it out of scope?

**Comment by OndraM** [comment]
@williamdes You mean into php-webdriver namespace? Is there any reason for it?

**Comment by williamdes** [comment]
@OndraM yes, I am no sure about my question
I was just thinking maybe It made sense
If it is an extension?

**Comment by OndraM** [comment]
I ment extension in terms of OOP, not in terms of some extension system :-).

However if there will be in future some project related to php-webdriver, which would need its namespace, we surely can discuss it.
