### ISSUE TITLE
Usefull Exception messages are discareded 

### ISSUE THREAD

**Issue by salarmehr** [php-webdriver/php-webdriver#595]
In `\Facebook\WebDriver\Remote\Service\DriverService::isRunning` we have 
```
            if (!$this->service->isRunning()) {
                throw new WebDriverException('The driver server has died.');
            }
```

This blocks spoilers the meaningful error message e.g. `no such element: Unable to locate element: {"method":"id","selector":"[aria-label*=Log]"}`  (from `Facebook\WebDriver\Exception\NoSuchElementException` with a hardcoded error message `The driver server has died`. That make debugging hard.  Line 65 (`throw $e;`) is not reachable in any way when `this->service->isRunning()` is true.  I can creat MR to fix it. 

* Php-webdriver version:  1.6.0
* PHP version: 7.1
* ChromeDriver 
* Operating system: Win 10 
* Browser used:  Chrome

**Comment by eduduardo** [comment]
A pull request for remove this condition and throw all exceptions will be very useful. It's really hard to debug without the exceptions.
