### ISSUE TITLE
Opera is not working

### ISSUE THREAD

**Issue by edvardpotter** [php-webdriver/php-webdriver#617]
### What are you trying to achieve?
I'm trying to run Opera Blink

### What do you get instead?
Facebook\WebDriver\Exception\SessionNotCreatedException
Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'VIP-NB', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.1'
Driver info: driver.version: unknown

### How could the issue be reproduced?
My php code:

```php
$capabilities = new DesiredCapabilities();
$capabilities->setBrowserName('operablink');
$capabilities->setCapability('chromeOptions', ['binary' => 'E:\\ProgrammsNew\\Opera\\launcher.exe']);
$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $capabilities);
```

* Php-webdriver version: 1.6.0
* PHP version: PHP 7.0
* Selenium server version: 3.141.59
* Operating system: Windows 10 x64
* Browser used + version: Opera Blink 56.0.3051.116

**Comment by OndraM** [comment]
There have been many changes in php-webdriver since this issue was originally reported, so please try with latest php-webdriver and if the issue still persist, please submit a new issue. Thank you!
