### ISSUE TITLE
driver session unaccessable after pageLoadTimeout exceptions in pages with long script link

### ISSUE THREAD

**Issue by irajtaghlidi** [php-webdriver/php-webdriver#625]
### What are you trying to achieve? (Expected behavior)
After try/catch with Exception on get() method, you should able to continue use driver instance.

### What do you get instead? (Actual behavior)
But after catch Exception and in next commands internal timeout occurred
(Facebook\WebDriver\Exception\TimeOutException: timeout) on every HttpCommandExecutor commands.

### How could the issue be reproduced? (Steps to reproduce)
create a php link in server with this content ( to get it with selenium) :
_we call it http://example.com/timeout.php for example here._
```
<html>
	<head>
		<title>Page with Timeout</title>
	</head>

	<body>
		<script src="https://httpstat.us/200?sleep=600000"></script>
	</body>
</html>
```

**Scenario # 1 (with problem)**
```php
$link1 = 'http://example.com/timeout.php'; // html response received but <script> link will not be complete before pageLoadTimeout value.
$driver->manage()->timeouts()->pageLoadTimeout(10);

try {
    $driver->get($link);
}
catch (\Exception $e) {
    \Log::debug('Exception: (Timeout)');
}

$driver->refresh(); // OR any other command to interact with browser.
```

**Scenario # 2 (without problem)**
```php
$link2 = 'https://httpstat.us/200?sleep=600000'; // main url will not be load in long time.
$driver->manage()->timeouts()->pageLoadTimeout(10);

try {
    $driver->get($link);
}
catch (\Exception $e) {
    \Log::debug('Exception: (Timeout)');
}

$driver->refresh(); // OR any other command to interact with browser.
```

In both scenarios I get catch exception Log output as `Exception: (Timeout)` text. so Exception called in both of them.

* In Laravel codes I used \Exception for test, but it has same result in TimeOutException, WebDriverException, WebDriverCurlException, OTHERS.

I use this component in Laravel, So it's my error trace for every command after main timeout exception lines.

`
Error
Facebook\WebDriver\Exception\TimeOutException: timeout
(Session info: chrome=71.0.3578.98)
(Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.19.8-1.el7.elrepo.x86_64 x86_64) in /PROJECT-HOME/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:130
Stack trace:
#0 /PROJECT-HOME/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(326): Facebook\WebDriver\Exception\WebDriverException::throwException(21, 'timeout\n (Sess...', Array)
#1 /PROJECT-HOME/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(547): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /PROJECT-HOME/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php(40): Facebook\WebDriver\Remote\RemoteWebDriver->execute('refresh', Array)
#3 /PROJECT-HOME/vendor/facebook/webdriver/lib/WebDriverNavigation.php(70): Facebook\WebDriver\Remote\RemoteExecuteMethod->execute('refresh')
#4 /PROJECT-HOME/app/Services/Supply/ProcessWays/MainProcessor.php(65): Facebook\WebDriver\WebDriverNavigation->refresh()
`

### Details

* Php-webdriver version: 1.6.0
* PHP version: 7.3.1
* Selenium server version: 3.141.59
* Operating system: Docker-Selenium [3.141.59-dubnium](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-dubnium)
Selenium: 3.141.59
Google Chrome: 71.0.3578.98
ChromeDriver: 2.45
GeckoDriver: 0.23.0

**Comment by OndraM** [comment]
Hi,
I'm closing this for now, as the issue it may no longer be relevant or may be outdated.

However, if the issue still persist, please try with latest version of php-webdriver, dusk and chromedriver and feel free to comment. 

Thank for your understanding
