### ISSUE TITLE
`findElementWithWait()` method?

### ISSUE THREAD

**Issue by walisc** [php-webdriver/php-webdriver#651]
Has they been thought about having something like a `findElementWithWait()` function

I know there is there is the `$driver->wait()->until()` logic (and it's not in the standard java api), but this is a bit cumbersome to always write, especially if the element you are looking for is a child of the parent element you are calling the find from. In this case you will need to write some function like

```php

    $parent = $this->driver->findElement(WebDriverBy::xpath("..."));
    $this->driver->wait()->until(
        function () use ($parent){
            try{
                return  $parent->findElement(WebDriverBy::xpath("...")) 
            }
            catch (NoSuchElementException $e){
                return null;
            }
        }
    );
    
    $parent->findElement($elementPath)->click()
}
```

And i know, you can just refactor this out (which I have done), but would be great if we can call this method on a parent item directly. i.e

```php
 $parent = $this->driver->findElement(WebDriverBy::xpath("..."));
 $parent->findElementWithWait(WebDriverBy::xpath("...."))->click()
 ```

Do you think this is something worth implementing?
 
### Details

* Php-webdriver version: 1.7.0
* PHP version: 7.2
* Selenium server version:  3.9.1
* Operating system: Ubuntu 18.02
* Browser used + version: Chrome 25

**Comment by OndraM** [comment]
Hi, thanks for the suggestion. However I think doing this syntax sugar is job of libraries built on top of php-webdriver (which is kinda low-level library).

For example in [Steward](https://github.com/lmc-eu/steward/), it [would be ](https://github.com/lmc-eu/steward/blob/43feefc255f77588215d18b90758a1a8ff05bea4/src/Test/SyntaxSugarTrait.php#L263)

```php
$this->wd->waitForXpath('//someXpath;)->click();
// or
$this->wd->waitForCss('.someCss')->click();
```
