### ISSUE TITLE
Missing "SameSite" attribute in cookies

### ISSUE THREAD

**Issue by codegain** [php-webdriver/php-webdriver#705]
### What are you trying to achieve? (Expected behavior)
If I have a cookie from webdriver I expect to read the "SameSite" attribute of the cookie.

### What do you get instead? (Actual behavior)
In https://github.com/facebook/php-webdriver/blob/community/lib/Cookie.php#L49 the "SameSite" attribute is not saved in the cookie.

### Details

* Php-webdriver version: 1.7.1
* PHP version: 7.3.11
* Operating system: CentOS 7
* Browser used + version: Chromium 77.0.3865.90
* Chromedriver used: ChromeDriver 77.0.3865.90

**Comment by OndraM** [comment]
Hi, unfortunately WebDriver protocol as of this day does not allow setting Same-Site attribute of cookie (as this feature is quite new), see https://w3c.github.io/webdriver/#cookies . So there is nothing we can do in `php-webdriver`.

You may follow issue https://github.com/w3c/webdriver/issues/1134 in W3C WebDriver protocol issue tracker - it seems this is planned to future "level 2" of the protocol. But it won't happen any time soon, I'm afraid.

**Comment by codegain** [comment]
@OndraM I think this has been implemented in https://github.com/w3c/webdriver/pull/1473. Chrome will ship "sameSite" cookie support with version 80.

**Comment by OndraM** [comment]
:+1: Nice, that was faster than I expected. Kudos @christian-bromann :1st_place_medal: 

FYI the Geckodriver issue is there: https://bugzilla.mozilla.org/show_bug.cgi?id=1606439

**Comment by andrewnicols** [comment]
The Geckodriver issue landed a few days ago so it should be possible to update this.

Do you think we need to support the old naming as a fallback somehow? Not sure if that’s even possible.

**Comment by OndraM** [comment]
Would be nice to have it implemented now, when it is actually implemented in the browsers, sure :+1: . What do you think as old naming? 

Also, not sure whether this needs to be handled differently in JsonWire (if it will or will not accept extra cookie parameters).
