### ISSUE TITLE
ElementToBeClickable doesn't actually guarantee the element is clickable

### ISSUE THREAD

**Issue by TheDutchCoder** [php-webdriver/php-webdriver#727]
### What are you trying to achieve? (Expected behavior)

Sometimes, async elements overlaying another element intercept clicks, even though `ElementToBeClickable` suggests that the underlying element is clickable (it's not)

### What do you get instead? (Actual behavior)

The method to return true only when the element *really* is clickable. When other items overlay it (like fixed position elements) the element is **not** clickable, even though it's in the DOM, visible, and ready.

### How could the issue be reproduced? (Steps to reproduce)

Just overlay a button with a fixed element.

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details

* Php-webdriver version: 1.8@dev
* PHP version: 7.3
* Selenium server version: 3.141.59-yttrium
* Operating system: Mac OS X Mojave
* Browser used + version: Chrome 76

**Comment by OndraM** [comment]
Hi, the `elementToBeClickable` is actually only shortcut to ensure the element is present, visible and not disabled (like disabled input button).

There is AFAIK no simple way in Selenium/WebDriver how to for example determine whether some overlay is blocking click to the element.

**Comment by TheDutchCoder** [comment]
Then why does it throw an exception saying that another element is in the way? Wouldn't that automatically mean there's some way to detect it?

**Comment by OndraM** [comment]
Well, you didn't provide the error you got, so we don't know what exactly is happening 🙂. 

Unfortunately there is no native WebDriver method which will tell whether something is obscuring the element before you actually execute the click. 

One would need to implement some javascript-based workaround, for example something like [Watir did here](https://jkotests.wordpress.com/2018/09/22/clearing-the-way-to-checking-clickability-via-elementobscured/).

**Comment by rernesto** [comment]
Element XYZ is not clickable at point (X,Y) because another element ABC obscures it .

Solution:

```php
//your code
       //make sure element is present in DOM
       $driver->wait()->until(
          WebDriverExpectedCondition::presenceOfElementLocated(
              WebDriverBy::xpath($elementXPath)
          )
        );

        $videoElement = $driver->findElement(WebDriverBy::xpath($elementXPath));
        
        //Only Click when it's clickable gonna works
        $driver->wait()->until(
            function () use ($driver, $videoElement) {
                try {
                    $driver->executeScript('console.log("clicking");');
                    $videoElement->click();
                } catch (WebDriverException $e) {
                    return false;
                }
                $driver->executeScript('console.log("clickable");');
                return true;
            }
        );
//your code
```

You're welcome ;)

**Comment by OndraM** [comment]
@andrewnicols However, this is not part of W3C, but in Java bindings this is polyfilled using javascript snippet: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec.java#L233-L236

We already use something similar for submit (submit is also not part of W3C), so I was thinking we could do something similar?

**Comment by andrewnicols** [comment]
Ah, fair enough. I'll re-open then.

It would be good to clarify what the limits of this driver are. To my mind we should mostly be adding the officially supported features and not adding too many polyfills unless they were part of JsonWire and no longer exists (or vice-versa).

**Comment by oleg-andreyev** [comment]
JFYI Here is Selenium implementation https://github.com/SeleniumHQ/selenium/blob/bf2fc564eeaeecfd980984119bd18d0a00bdb29e/java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java#L627

**Comment by OndraM** [comment]
This sounds like the same story as in https://github.com/php-webdriver/php-webdriver/issues/843#issuecomment-756318427 🤔

I'm afraid we're not able to resolve those issues without implementing something like the javascript atoms in Java bindings. I'm curious, whether all the language libraries do the same on how do they take care of these features like "displayed" or "clickabe", which are not part of W3C spec.

**Comment by JuGid** [comment]
Can you just verify if an element is on top of the element position without that much overhead ? 
I know that selenium can say if an element is clickable (displayed and enabled) but does not guarantee that the element is clickable and this force you to use the Javascript executor by returning an Exception (the element ... will receive the click)  
Also, I want to ask why this could be a "feature" since the use of WebDriver is mostly to simulate what you can do on browsers and if an element is overlayed, the user (or you) cannot click on the element. We (Php-webdriver users) should verify if the element that is overlaying the element is visible. Does a clickable element mean that you can click on it ?

**Comment by andrewnicols** [comment]
Just to add to the picture here, I’ve spent the better part of a week trying to track down a bug in [chromedriver](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3933) which I _believe_ to be a bug in the use of the `scrollRegionIntoView` atom and was an absolute nightmare to debug because of the way in which atoms are included in Chromedriver itself.
