### ISSUE TITLE
TimeOutException when testing on ubuntu server but no localhost..

### ISSUE THREAD

**Issue by MemorialDev** [php-webdriver/php-webdriver#737]
### What are you trying to achieve? (Expected behavior)
Hello,

im getting this error when running script on ubuntu server but no localhost..
In localhost using: #chromedriver77 #selenium-server-standalone-3.9.0 #chrome v78

and on my ubuntu latest version of selenium, chromedriver 79 and chrome v 79.
What is the problem? thanks you..

PS: Im running the script without "-enablePassThrough false" do I need to run it with on ubuntu?
Thanks you!

Fatal error: Uncaught Facebook\WebDriver\Exception\TimeOutException in /var/www/html/vendor/facebook/webdriver/lib/WebDriverWait.php:84 Stack trace: #0 /var/www/html/script.php(48): Facebook\WebDriver\WebDriverWait->until() #1 {main} thrown in /var/www/html/vendor/facebook/webdriver/lib/WebDriverWait.php on line 84

* Php-webdriver version: chromedriver 79
* PHP version: 7.4.1
* Selenium server version: Last version
* Operating system: Ubuntu 16.04
* Browser used + version: Chrome v79

**Comment by OndraM** [comment]
Hi, please provide the full error you get, the code you execute and the commands you use to start chromedriver/selenium - otherwise it hard for anyone to help.
