### ISSUE TITLE
Clean the webdriver "Hub"

### ISSUE THREAD

**Issue by MemorialDev** [php-webdriver/php-webdriver#741]
Hello,

Im looking to clear the webdriver "hub", because after 17 run, I cannot re-use the webdriver anymore I have to delete manually the sessions..

Thanks you..

* Php-webdriver version: Last
* PHP version: Last
* Selenium server version: Last
* Operating system: 16.04 Ubuntu
* Browser used + version: Chrome Last

**Comment by andrewnicols** [comment]
Hi @MemorialDev,

When opening issues please follow the issue template. It sounds like your code is wrong and that you are just not closing the WebDriver instance at the end of your test.

https://github.com/php-webdriver/php-webdriver/blob/community/lib/Remote/RemoteWebDriver.php#L190
