### ISSUE TITLE
Unable to find handler for (POST) /wd/hub/session

### ISSUE THREAD

**Issue by JoeyofBladez** [php-webdriver/php-webdriver#743]
### What are you trying to achieve? (Expected behavior)
Run tests like I used to before I updated versions of software. Specifically, I am trying to instantiate a new RemoteWebDriver object using the static "create" method and I am getting an exception from WebDriver

### What do you get instead? (Actual behavior)
`Facebook\WebDriver\Exception\UnknownCommandException: Unable to find handler for (POST) /wd/hub/session`

### How could the issue be reproduced? (Steps to reproduce)
First,initialize the environment and get selenium running locally:
```
$ Xvfb :99 -screen 5 1920x1080x8 &
$ export DISPLAY=:99
$ java -Dwebdriver.chrome.driver="./chromedriver" -jar selenium-server-4.0.0-alpha-4.jar standalone
```

Then, call phpunit to run tests: 
`./phpunit-8.5.2.phar --bootstrap test-config.php /path/to/tests`

PHP code is called:
```$options = new ChromeOptions();
$options->addArguments(array('--headless', '--window-size=1920,1080'));
$caps= DesiredCapabilities::chrome();
$caps->setCapability(ChromeOptions::CAPABILITY, $options);
$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $caps); // this line throws exception
$driver->manage()->window()->maximize();
```

### Details
Google Chrome 79.0.3945.130
ChromeDriver 79.0.3945.36
selenium-server-4.0.0-alpha-4.jar
Newest code from the php-webdriver GitHub as of 1/22/2020
CentOS Linux release 7.7.1908 (Core)

**Comment by andrewnicols** [comment]
Hi @JoeyofBladez,

Selenium 4 changes the URL. It's no longer behind `/wd/hub`. The error is correct. It does not know what `/wd/hub/session` means. The new URL is `http://localhost:4444` which would make the new session URL `http://localhost:4444/session`.

You can view the status at http://localhost:4444/status

**Comment by JoeyofBladez** [comment]
Thank you very much! That certainly got me past this error.
