### ISSUE TITLE
Executing Chrome Devtools Protocol commands

### ISSUE THREAD

**Issue by bugsbunch** [php-webdriver/php-webdriver#753]
### What are you trying to achieve? (Expected behavior)
Hi! I need to execute Chrome Devtools Protocol commands, in particular,
set Page.addScriptToEvaluateOnNewDocument option

### What do you get instead? (Actual behavior)
i didn't found webdriver method

Thank you!

* Php-webdriver version: 1.7.1
* PHP version: 7.2
* Selenium server version: 3.10
* Operating system: mac os 10.14
* Browser used + version: Google Chrome 80

**Comment by OndraM** [comment]
Hi, there is already (unfinished) pull request to add chrome dev tools support: #556 .

**Comment by Hippo0o** [comment]
i stumbled upon the same problem today and got it working with this (using code from the PR)
```php
$driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
  'cmd'    => 'Page.addScriptToEvaluateOnNewDocument',
  'params' => (object)[
    "source" => "
    Object.defineProperty(navigator, 'webdriver', {
      get: () => undefined
    })",
  ],
]);
```

**Comment by umarsaid** [comment]
> i stumbled upon the same problem today and got it working with this (using code from the PR)
> 
> ```
> $driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
>   'cmd'    => 'Page.addScriptToEvaluateOnNewDocument',
>   'params' => (object)[
>     "source" => "
>     Object.defineProperty(navigator, 'webdriver', {
>       get: () => undefined
>     })",
>   ],
> ]);
> ```

It does not seem to work.

**Comment by GeorgeGalway** [comment]
> i stumbled upon the same problem today and got it working with this (using code from the PR)
> 
> ```
> $driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
>   'cmd'    => 'Page.addScriptToEvaluateOnNewDocument',
>   'params' => (object)[
>     "source" => "
>     Object.defineProperty(navigator, 'webdriver', {
>       get: () => undefined
>     })",
>   ],
> ]);
> ```

It looks like you are missing a double quote
`$this->_driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
            'cmd' => 'Page.addScriptToEvaluateOnNewDocument',
            'params' => (object)[
                "source" => "\"
                    Object.defineProperty(navigator, 'webdriver', {
                    get: () => false,
                })\"",
            ],
        ]);`

**Comment by GeorgeGalway** [comment]
> > i stumbled upon the same problem today and got it working with this (using code from the PR)
> > ```
> > $driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
> >   'cmd'    => 'Page.addScriptToEvaluateOnNewDocument',
> >   'params' => (object)[
> >     "source" => "
> >     Object.defineProperty(navigator, 'webdriver', {
> >       get: () => undefined
> >     })",
> >   ],
> > ]);
> > ```
> 
> It does not seem to work.

It looks like you are missing a double quote, please see previous reply.

**Comment by Hippo0o** [comment]
> > i stumbled upon the same problem today and got it working with this (using code from the PR)
> > ```
> > $driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
> >   'cmd'    => 'Page.addScriptToEvaluateOnNewDocument',
> >   'params' => (object)[
> >     "source" => "
> >     Object.defineProperty(navigator, 'webdriver', {
> >       get: () => undefined
> >     })",
> >   ],
> > ]);
> > ```
> 
> It does not seem to work.

In later version of chrome it seems to be impossible to manipulate navigator.webdriver. It will return false on the normal browser and with certain flags in chromedriver aswell.

**Comment by GeorgeGalway** [comment]
> > > i stumbled upon the same problem today and got it working with this (using code from the PR)
> > > ```
> > > $driver->executeCustomCommand('/session/:sessionId/chromium/send_command', 'POST', [
> > >   'cmd'    => 'Page.addScriptToEvaluateOnNewDocument',
> > >   'params' => (object)[
> > >     "source" => "
> > >     Object.defineProperty(navigator, 'webdriver', {
> > >       get: () => undefined
> > >     })",
> > >   ],
> > > ]);
> > > ```
> > 
> > 
> > It does not seem to work.
> 
> In later version of chrome it seems to be impossible to manipulate navigator.webdriver. It will return false on the normal browser and with certain flags in chromedriver aswell.

Chrome: 88.0.4324.96 is work : )
