### ISSUE TITLE
Add additional members to the project

### ISSUE THREAD

**Issue by andrewnicols** [php-webdriver/php-webdriver#760]
Hi @OndraM ,

I'm thinking it would be good to have a few more people able to help you on the project. Whether that's initially just helping to close invalid bugs, or actually having push commit access is up to you, but it would be good to begin that discussion.

@williamdes may also have some thoughts on this as a regular contributor.

**Comment by williamdes** [comment]
Good idea, just triage and improving coverage and bug fixes could help the project.
I have no bandwidth for triage and support because I have a lot to track on phpMyAdmin but I would like to help review PRs.

**Comment by andrewnicols** [comment]
I'm also happy to do PRs. I don't have any real time for bandwidth but I've already been trying to assist with the triage.

I'm extremely busy with Moodle too, but we rely on Behat so the stability, reliability, and continuing success of this project is important to us too.

**Comment by williamdes** [comment]
Thank you @OndraM

**Comment by OneEyedSpaceFish** [comment]
I'm also more than happy to review some PRs occasionally
Unfortunately I'm too busy to be doing anything more than that for the time being :(

**Comment by OndraM** [comment]
I thinks this is solved, but if anyone is willing to triage issues or join the maintainers team, he/she is more than welcomed! Reach us out directly by e-mail or write in [Discussions](https://github.com/php-webdriver/php-webdriver/discussions).

**Comment by andrewnicols** [comment]
@OndraM, does that mean that there are others on the maintainer list?

**Comment by OndraM** [comment]
@andrewnicols There are currently three of us. But sure I'm open about adding someone else if he/she is interested. 

We can also adjust our roles if we agree on some shared rules, so that there is not that much relying on me :). What do you think @andrewnicols @williamdes ?

**Comment by williamdes** [comment]
I would agree to share rules but to agree to always have one review before merging
I do not like very much the mode of where you are not the original author and you decide to merge work because nobody else can review.
You get the idea I would want to avoid :)

**Comment by andrewnicols** [comment]
I agree that some shared rules are important.

For me the important ones are:
1. self-merging is should be avoided except in emergency release, or unable to get a review in a reasonable amount of time
1. new features need agreement in some form - maybe from at least two of us, or must be a part of the W3C spec. There are some features which are not part of the spec and it would just be good to agree what the scope of the project is on those.
