### ISSUE TITLE
PHPWebDriver 1.8.0 with file TimeoutException in composer.json can't be loaded

### ISSUE THREAD

**Issue by michaljusiega** [php-webdriver/php-webdriver#762]
During CI/CD Jobs with Symfony Lint I got a fatal error with loading a TimeoutException. 

### What are you trying to achieve? (Expected behavior)
```
$ php bin/console lint:container --env=prod --no-debug
Job succeeded
```

### What do you get instead? (Actual behavior)
```
$ php bin/console lint:container --env=prod --no-debug
Fatal error: require(): Failed opening required '/builds/project/mytest/vendor/composer/../php-webdriver/webdriver/lib/Exception/TimeoutException.php' (include_path='.:/usr/local/lib/php') in /builds/project/mytest/vendor/composer/autoload_real.php on line 66
ERROR: Job failed: exit code 1
```

### How could the issue be reproduced? (Steps to reproduce)
As Expected behavior.
Create new project with Symfony. Install newest Symfony Panther too.

### Details
* Php-webdriver version: 1.8.0
* PHP version: 7.4.2
* Selenium server version: n/a
* Operating system: Gitlab CI/CD on Docker
* Browser used + version: n/a
* Symfony 4.4.4

### Suggest
I think `composer.json` should looks like:

```
  "autoload": {
    "psr-4": {
      "Facebook\\WebDriver\\": "lib/"
    }
  },
```
not

```
  "autoload": {
    "files": [
      "lib/Exception/TimeoutException.php"
    ],
    "psr-4": {
      "Facebook\\WebDriver\\": "lib/"
    }
  },
```

because composer generated to `autoload_files.php` and `autoload_static.php` a line:
` '2a3c2110e8e0295330dc3d11a4cbc4cb' => $vendorDir . '/php-webdriver/webdriver/lib/Exception/TimeoutException.php',`

which means that in theory there is no such file.

**Comment by OndraM** [comment]
This is probably outcome of #686 and #697. 

Basically `TimeOutException.php` was renamed to `TimeoutException.php`. And `TimeoutException.php` was added to autoloading to be loaded everytime, so that it will be available if you import it using the old casing (`use Facebook\WebDriver\Exception\TimeOutException;`).

@Lctrs maybe you could have look? It seemed for me this should never happen :smile:

**Comment by OndraM** [comment]
@michaljusiega Could you please provide exact reproducible case? Or maybe link to CI build, if its public? I just tried with clean symfony installation and it worked for me:

```
$ symfony new symfony_project --full // I tried also with version 4.4 with the same result
$ cd symfony_project
$ composer req symfony/panther
$ php bin/console lint:container --env=prod --no-debug // no error
```

**Comment by Lctrs** [comment]
Just tested locally with provided steps. Can't reproduce. Everything works fine.

@michaljusiega Do you have the latest composer version ?

**Comment by michaljusiega** [comment]
After my work, I'll try something.

**Comment by michaljusiega** [comment]
Okey, everything is fine with this file. The update from 1.7.1 to 1.8.0 turned out to be a problem. Composer caused that TimeOutException was not replaced with the correct TimeoutException, next trying later to load a TimeoutException that does not exist ... Strange.

So I close it, sorry for a false alarm.
