### ISSUE TITLE
SendKeys receive error "invalid argument: 'text' must be a string" when reusing the chrome session

### ISSUE THREAD

**Issue by zhi-hao** [php-webdriver/php-webdriver#771]
### What are you trying to achieve? (Expected behavior)
Able to use sendKeys() after reuse existing active chrome session for automation. 

### What do you get instead? (Actual behavior)
Received "Facebook\WebDriver\Exception\InvalidArgumentException  : invalid argument: 'text' must be a string" error when trying to send text to input using sendKeys()

### How could the issue be reproduced? (Steps to reproduce)
here are the sample code to reproduce the issue
```
        // create new session
        $host = 'http://localhost:9515';
        $driver = RemoteWebDriver::create(
                 $host, 
                 DesiredCapabilities::chrome(),
                 5000, 
                 60000
         );
        $driver->manage()->window()->maximize();
        $session_id = $driver->getSessionID();
        $driver->get('http://www.google.com');
        $driver->wait(5)->until(
             WebDriverExpectedCondition::visibilityOfElementLocated(
                    WebDriverBy::xpath('//input[@name="q"]')
             )
         )->sendKeys('Hi');
        sleep(1);
        
        // recreate the driver using previous session id
        $driver = RemoteWebDriver::createBySessionID($session_id, $host);
        $driver->get('http://www.google.com');
        $driver->wait(5)->until(
               WebDriverExpectedCondition::visibilityOfElementLocated(
                      WebDriverBy::xpath('//input[@name="q"]')
                )
         )->sendKeys('Error');
```

### Details
if the driver is freshly created from RemoteWebDriver::create(), it does not have any issue. However, when reuse previous chrome session by RemoteWebDriver::createBySessionID(), it run into error.

* Php-webdriver version: 1.8.1
* PHP version: 7.3.9
* Selenium server version: chromedriver_mac64 v80.0.3987.106
* Operating system: macOS 10.15.3
* Browser used + version: Google Chrome v80.0.3987.116

**Comment by OndraM** [comment]
Hi, thanks for the report! This is really improper behavior. I prepared fix in #772, it should be part of next php-webdriver release.
