### ISSUE TITLE
WebDriverBy::name() throws invalid locator exception

### ISSUE THREAD

**Issue by patrickomeara** [php-webdriver/php-webdriver#774]
After upgrading to 1.8.1 from 1.7 `WebDriverBy::name()` is throwing `PHPUnit\Framework\ExceptionWrapper  : invalid argument: invalid locator`

### How could the issue be reproduced? (Steps to reproduce)
```php
// not working
$webdriver->findElement(WebDriverBy::name('filter'));

// this does work
$webdriver->findElement(WebDriverBy::xpath("//select[@name='filter']"));
```

### Details

* Php-webdriver version: 1.8.1
* PHP version: 7.4.2
* Selenium server version: selenium/standalone-chrome:3.141.59-zirconium
* Operating system: Docker Ubuntu
* Browser used + version: 80.0.3987.106

**Comment by OndraM** [comment]
@patrickomeara Hi, thanks for the report. However I'm unable to reproduce the issue and it works form me properly. However in W3C mode the "name" WebDriverBy is actually internally translated to CSS selector like `[name='filter']`, so hypothetically, there may be an issue.

Could you please provide some reproducible case? Including HTML page where the issue occurs.

Also could you provide log from Selenium server (started with `-debug` option).

Thanks!

**Comment by patrickomeara** [comment]
Hi @OndraM thanks for looking into this. I think the issue occurs only after the DOM has been replaced. ie the `select[@name='filter']` element is removed and re-added to the DOM then webdriver tries to look for it, and fails. Is there a DOM cache that webdriver uses to find elements that may not be receiving updates?

It's strange that the xpath still works.

I'll do some more digging and report back.

**Comment by andrewnicols** [comment]
@patrickomeara, do you have a sample we can look at?

**Comment by patrickomeara** [comment]
This is only failing in my docker based CI. 

It is passing locally so my initial problem can be ignored. 

Thanks for your help

**Comment by ifokkema** [comment]
Although this issue is closed, I'd like to add that I have the same problem.
Also only on my Travis CI (and also, not locally). **Downgrading php-webdriver to 1.7 fixed the issue.**

Using Firefox:
"InvalidArgumentException: unknown variant `name`, expected one of `css selector`, `link text`, `partial link text`, `tag name`, `xpath`".

Using Chrome:
"invalid argument: invalid locator".

**Comment by OndraM** [comment]
@ifokkema Could you please try to isolate the issue and provide the code you run, which causes the error?

Also if you'd post version of Chrome, Chromedriver, Selenium server you use, it would be really helpful.

Thanks you!

**Comment by ifokkema** [comment]
I will try to do that tomorrow! I think I might be able to reproduce it locally as well.

**Comment by ifokkema** [comment]
OK, while reducing the code to a minimal example, the error disappeared when I removed my overloading of findElement(); internally, `$params` changed from:
```php
        $params = ['using' => $by->getMechanism(), 'value' => $by->getValue()];
```
to

```php
        JsonWireCompat::getUsing($by, $this->isW3cCompliant)
```

which makes all the difference. Updating my overloaded function fixes the problem. Sorry for the noise!
