### ISSUE TITLE
autoload.php error

### ISSUE THREAD

**Issue by Gadzillion** [php-webdriver/php-webdriver#781]
### What are you trying to achieve? (Expected behavior)

I'm trying to run example.php test. autoload.php exist. 
### What do you get instead? (Actual behavior)

```
PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\php-7.2.29-Win32-VC15-x64\pear') in C:\Users\...\tests\FirstTest.php on line 12
```

### How could the issue be reproduced? (Steps to reproduce)

FirstTest.php

```php
<?php

use Facebook\WebDriver\Chrome\ChromeDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once("vendor/autoload.php");
$host = 'http://localhost:9515/wd/hub';
putenv('WEBDRIVER_CHROME_DRIVER=chromedriver.exe');
$driver = ChromeDriver::start();
$driver->get('https://en.wikipedia.org/wiki/Selenium_(software)');
```

composer.json

```json
{
    "require": {
        "php-webdriver/webdriver": "^1.8"
    }
}
```

php.ini

```ini
include_path=".;C:\php-7.2.29-Win32-VC15-x64\pear"
```

### Details

* PEAR Version: 1.10.12
* Php-webdriver version: 1.8.2
* PHP version: 7.2.29
* Operating system: Win 10
* Browser used + version: Chrome 81

**Comment by williamdes** [comment]
did you `composer install` ?

**Comment by Gadzillion** [comment]
@williamdes yes
In addition: Now that I run the test via the command line 
```php
php FirstTest.php
``` 
everything works, but when I try to run through PHPStorm, an error still appears.

**Comment by williamdes** [comment]
Try `require_once __DIR__ . '/vendor/autoload.php';`
I hope It will fix the error in both cases

**Comment by Gadzillion** [comment]
@williamdes 
Structure of my project is 
![image](https://user-images.githubusercontent.com/44111308/79985980-09b41d00-84b4-11ea-84a5-165bee7a1211.png)

```php
require_once(__DIR__ . '..\vendor\autoload.php');
```
give me the same error

**Comment by Gadzillion** [comment]
@williamdes oh thx)
