### ISSUE TITLE
Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST

### ISSUE THREAD

**Issue by ildarius** [php-webdriver/php-webdriver#783]
### What are you trying to achieve? (Expected behavior)
Just did a fresh install via composer and running a single line of code to get to a web-site (after setting up the browser), but it returns an error.

Not sure if it's releated to dependencies

What's strange is that when installing it via
php require php-webdriver/webdriver it only created 3 folders (composer, php-webdriver, symfony) and doing composer update does not add any additional folders. I also tried copying over the composer.json and running the "composer install" but this time it setups up a larger amount of files but there's no **autoload.php**

### What do you get instead? (Actual behavior)
Error
```Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome"}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY"}}```

```
Operation timed out after 30004 milliseconds with 0 bytes received in /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:331
Stack trace:
#0 /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(136): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 /Applications/MAMP/htdocs/selenium/scraper.php(23): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities))
#2 {main}
  thrown in /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php on line 331
```

### How could the issue be reproduced? (Steps to reproduce)
Installed the dependencies via composer and executed the test script

```php

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
require_once(__DIR__ . '/vendor/autoload.php');

$host = 'http://localhost:4444/wd/hub';

$driver = RemoteWebDriver::create(
    $host,
    DesiredCapabilities::chrome()
);

$driver->get("http://somesite.com");

```

### Details

* Php-webdriver version: 1.8
* PHP version: 7.1.33
* Selenium server version: selenium-server-standalone-3.141.59.jar
* Operating system: MacOS
* Browser used + version: ChromeDriver 81.0.4044.69

**Comment by ildarius** [comment]
![Screen Shot 2020-04-24 at 2 47 51 AM](https://user-images.githubusercontent.com/1866104/80185135-d7044480-85d9-11ea-8169-08dc334ea16f.png)

that's all the files that get setup when running composer install, not sure if it's normal

**Comment by williamdes** [comment]
@ildarius Could you fence all the traces and code blocks you send, please :)
```` ```json/php/(empty) ````
```` ``` ````

**Comment by williamdes** [comment]
I would recommend to delete the 3 folders and to `composer update`
That will create the vendor folders in `vendor` and create the `autoload.php` file

**Comment by ildarius** [comment]
@williamdes thank you for the reply, just fenced everything. I deleted vendor folder and ran composer update and see the following, so looks like it hasn't changed. There should be more folders in vendor than this right?
![Screen Shot 2020-04-24 at 3 32 32 AM](https://user-images.githubusercontent.com/1866104/80186639-4f6c0500-85dc-11ea-96fb-678f511db8cc.png)

**Comment by williamdes** [comment]
@ildarius Thank you :relieved: 

for example
```
--- /
--- /vendor
--- /src
--- /src/myfile.php
```
Would give `require_once(__DIR__ . '/../vendor/autoload.php');`

So, for me there is no vendor or auto-loader bug but a connectivity bug.
Did you start a Selenium hub ?
Do you have docker ?

**Comment by ildarius** [comment]
you're right, I didn't notice there was an error when starting up the server, I resolved and and relaunched the test script from example.php and it's returning the following error now

`
Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Ildars-iMac.local', ip: '192.168.2.12', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '14.0.1'
Driver info: driver.version: unknown in /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:125
Stack trace:
#0 /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(370): Facebook\WebDriver\Exception\WebDriverException::throwException('session not cre...', 'Unable to creat...', Array)
#1 /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(136): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /Applications/MAMP/htdocs/selenium/test2.php(15): Facebook\WebDriver\Remote\ in /Applications/MAMP/htdocs/selenium/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php on line 125
`

**Comment by williamdes** [comment]
@ildarius How do you run the selenium server/hub ?

**Comment by ildarius** [comment]
@williamdes i do 
$ java -jar selenium-server-standalone-3.141.59.jar

**Comment by williamdes** [comment]
This is strange, you are up to date and something seem not to work when creating sessions.
I not not know to help you more for now maybe @OndraM has an idea

I would recommend to try using a docker version https://github.com/wdesportes/phpmyadmin-local-setup/blob/cd1386bb0528ee35a316eab28b0cb9f872a01543/docker-compose.yml#L553

**Comment by ildarius** [comment]
Here's the solution to my problem once the server issue got fixed https://github.com/SeleniumHQ/selenium/issues/4818#issuecomment-375087580

just dropped the chromedriver executable into the same folder as the javascript server executable

Merci bcp pour ton temps, c'est tres apprecié!

**Comment by williamdes** [comment]
> Merci bcp pour ton temps, c'est tres apprecié!

Merci !
Bon testing ;)
