### ISSUE TITLE
unknown command: Cannot call non W3C standard command while in W3C mode for getLocationOnScreenOnceScrolledIntoView()

### ISSUE THREAD

**Issue by dees040** [php-webdriver/php-webdriver#794]
### What are you trying to achieve? (Expected behavior)
I'm trying to scroll down to the correct element using the `$element->getLocationOnScreenOnceScrolledIntoView()` method.

### What do you get instead? (Actual behavior)

When executing the method I get the following error: unknown command: Cannot call non W3C standard command while in W3C mode. In `Facebook\WebDriver\Exception\UnknownCommandException`

### How could the issue be reproduced? (Steps to reproduce)

```php
$element = $driver->findElement($by);
$element->getLocationOnScreenOnceScrolledIntoView();
```

I'm not sure if this is suppose to happen. The error states that I should create a none w3c compliant driver/session. I tried that as well, without luck. `isW3cCompliant` is always true. My original driver initialisation:

```php
$options = new ChromeOptions();
$capabilities = DesiredCapabilities::chrome();

$capabilities->setCapability('chromeOptions', $options);
$capabilities->setCapability('goog:chromeOptions', [
    'args' => [
        'user-data-dir=', // Removed actual dir for this post
    ],
]);

// Create a new driver with a new session.
$driver = RemoteWebDriver::create($this->host, $capabilities);
```

### Details

* Php-webdriver version: 1.8
* PHP version: 7.4
* Selenium server version: 3.9.1
* Operating system: macOS Catalina
* Browser used + version: Chrome 83.0.4103.61

**Comment by OndraM** [comment]
Hi, you are using command, which is no longer supported in W3C WebDriver protocol (`getLocationOnScreenOnceScrolledIntoView()`) and you should use appropriate replacement, but it may also not be necessary to make this call altogether.

What is the purpose of using this call? What are you trying to achieve by this?

```php
$element->getLocationOnScreenOnceScrolledIntoView();
```

You are not using the returned value (element location), so I guess you just want to scroll the webpage so that the element is in current view? Why? What do you execute right after the code you posted?

**Comment by dees040** [comment]
I fixed it using the following code:
```php
$element = $driver->findElement($by);
$action = new WebDriverActions($this->driver);
$action->moveToElement($element);
$action->perform();
```

The reason why I need to scroll down is to get a certain element to show in the DOM. I've a large list with hundreds of items. The list loads the correct items to show based on your position. So I need to scroll down to be able to click on the element which I'm looking for.

Thanks for your help.

**Comment by ADR1418** [comment]
what class did you use to execute that action?

**Comment by dees040** [comment]
> what class did you use to execute that action?

`WebDriverActions` or which 'class' are you referring about a DOM class or one of the package PHP classes?

**Comment by ADR1418** [comment]
Im having a problem on app which is scroll to element. I tried to replicate your code but Im getting this:
<img width="939" alt="Screen Shot 2021-09-16 at 12 29 23 PM" src="https://user-images.githubusercontent.com/90681872/133549550-60230112-bb0d-4067-af5a-391a8ad470b1.png">

I use this code:
<img width="687" alt="Screen Shot 2021-09-16 at 12 30 32 PM" src="https://user-images.githubusercontent.com/90681872/133549643-ac219942-2013-4653-887a-02459bfa5800.png">
