### ISSUE TITLE
php-webdriver Undefind index

### ISSUE THREAD

**Issue by AhmedHassanReyad** [php-webdriver/php-webdriver#798]
### What are you trying to achieve? (Expected behavior)
selenium/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php on line 208

### What do you get instead? (Actual behavior)

selenium/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php on line 208
![Screenshot from 2020-06-15 03-07-20](https://user-images.githubusercontent.com/47591652/84609022-61b84000-aeb5-11ea-8455-6e1a7edbcb32.png)

### How could the issue be reproduced? (Steps to reproduce)
i try to automation php file but i got error selenium/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php on line 208 

```php
$driver->get("http://www.google.com");
$driver->findElement(Facebook\WebDriver\WebDriverBy::id('lst-ib'))->click();
$driver->findElement(Facebook\WebDriver\WebDriverBy::id('lst-ib'))->sendKeys('programster selenium');
$driver->findElement(Facebook\WebDriver\WebDriverBy::name('btnK'))->click();
```

### Details

* Php-webdriver version: https://github.com/php-webdriver/php-webdriver
* PHP version: 7.4
* Selenium server version: 3.141.59
* Operating system: Ubuntu 20.04
* Browser used + version: Chrome . 83.0.4103.61

**Comment by OndraM** [comment]
Hi, you may be using outdated version of php-webdriver. 

Please provide php-webdriver version you used - you can check it out using command `composer show php-webdriver/webdriver` (look for "version").

Also, please provide full content of `test.php` file.

**Comment by AhmedHassanReyad** [comment]
> composer show php-webdriver/webdriver

**Comment by AhmedHassanReyad** [comment]
> > composer show php-webdriver/webdriver

In ShowCommand.php line 207   Package php-webdriver/webdriver not found

**Comment by OndraM** [comment]
You are not using latest php-webdriver version. This is also why it fails with new chrome.

Have a look at https://github.com/php-webdriver/php-webdriver/blob/master/README.md#upgrade-from-version-180 and upgrade.

**Comment by AhmedHassanReyad** [comment]
> You are not using latest php-webdriver version. This is also why it fails with new chrome.
> 
> Have a look at https://github.com/php-webdriver/php-webdriver/blob/master/README.md#upgrade-from-version-180 and upgrade.

Ondram i have a latest version i don;t what problem can u help me remot if u can please

**Comment by AhmedHassanReyad** [comment]
test.php
<?php

require_once(__DIR__ . '/vendor/autoload.php');

$host = 'http://localhost:4444/wd/hub'; // this is the default
$USE_FIREFOX = true; // if false, will use chrome.

if ($USE_FIREFOX)
{
    $driver = Facebook\WebDriver\Remote\RemoteWebDriver::create(
        $host, 
        Facebook\WebDriver\Remote\DesiredCapabilities::firefox()
    );
}
else
{
    $driver = Facebook\WebDriver\Remote\RemoteWebDriver::create(
        $host, 
        Facebook\WebDriver\Remote\DesiredCapabilities::chrome()
    );
}

$driver->get("http://www.google.com");

# enter text into the search field
$driver->findElement(Facebook\WebDriver\WebDriverBy::id('lst-ib'))->click();
sleep(1);
$driver->findElement(Facebook\WebDriver\WebDriverBy::id('lst-ib'))->sendKeys('programster selenium');
sleep(1);

# Click the search button
$driver->findElement(Facebook\WebDriver\WebDriverBy::name('btnK'))->click();

**Comment by AhmedHassanReyad** [comment]
<?php

require_once(__DIR__ . '/vendor/autoload.php');

$host = 'http://localhost:4444/wd/hub'; // this is the default
$USE_FIREFOX = true; // if false, will use chrome.

if ($USE_FIREFOX)
{
    $driver = Facebook\WebDriver\Remote\RemoteWebDriver::create(
        $host, 
        Facebook\WebDriver\Remote\DesiredCapabilities::firefox()
    );
}
else
{
    $driver = Facebook\WebDriver\Remote\RemoteWebDriver::create(
        $host, 
        Facebook\WebDriver\Remote\DesiredCapabilities::chrome()
    );
}

$driver->get("http://www.google.com");

# enter text into the search field
$driver->findElement(Facebook\WebDriver\WebDriverBy::id('lst-ib'))->click();
sleep(1);
$driver->findElement(Facebook\WebDriver\WebDriverBy::id('lst-ib'))->sendKeys('programster selenium');
sleep(1);

# Click the search button
$driver->findElement(Facebook\WebDriver\WebDriverBy::name('btnK'))->click();
