### ISSUE TITLE
sendKeys() issue : no whitespace and sending TAB instead of '6'

### ISSUE THREAD

**Issue by Bougagi** [php-webdriver/php-webdriver#802]
### What are you trying to achieve? (Expected behavior)
I want to send a phone number in a phone number input. Phone number is a french number like 06xxxxxxxx, x being number.

### What do you get instead? (Actual behavior)
The phone input gets the '0' and the next input gets the 'xxxxxxxx'. The '6' disapeared like it is consued like  a key TAB command.

### How could the issue be reproduced? (Steps to reproduce)
can be reproduced simply by going on google.com and sending to the input search '0600'. '0' is written and that's all.

```php
$driver -> get('https://google.com');
$driver->findElement(WebDriverBy::xpath("//input[@title='Search']"))->sendKeys('0600');
```

### Details
whitespaces are also not displayed and written.

* Php-webdriver version: 1.8.2
* PHP version: 7.2.24
* Selenium server version: Using Chromedriver for chrome 83
* Operating system: Ubuntu 18.04.6
* Browser used + version: chromium 83

**Comment by OndraM** [comment]
@Bougagi It does work form me, though:

![obrazek](https://user-images.githubusercontent.com/793041/85393256-fb828b80-b54c-11ea-86c5-ee986d309513.png)

Also out testsuite which includes tests which use sendKeys works fine. So it may be an issue on your side?

Could you try to isolate the issue? Also have a look at Chromedriver output - you can investigate the responses rom Chromedriver, to see whether it receives "sendKeys" command properly etc.

**Comment by Bougagi** [comment]
hey thanks for your fast reply. I've isolated the issue in a new php file. Here is the code:
```php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once('vendor/autoload.php');

$host = 'http://localhost:4444/';
$driver = RemoteWebDriver::create($host, DesiredCapabilities::chrome());
$driver -> get('https://google.com');
$driver->findElement(WebDriverBy::xpath("//input[@title='Search']"))->sendKeys('0600');
```
Maybe i do something wrong.

I don't know how to investigate the responses from Chromedriver. Can you explain how to if you have time please ? I guess the whitespaces issue is also related to it.
Thanks

**Comment by Bougagi** [comment]
When changing the string from '0600' to '0 0600', i even have a search for '0' like this :
![issue](https://user-images.githubusercontent.com/36695741/85395927-2c64bf80-b551-11ea-8ac2-b7deed582e82.PNG)

Just before the research i can see that '00' has been entered to the input for a short moment and then it searchs for '0'.

**Comment by OndraM** [comment]
> Can you explain how to if you have time please ? I guess the whitespaces issue is also related to it.

How do you start Selenium server / Chromedriver? Does it output some errors?

Also, make sure you use compatible Chrome / Chromedriver version

**Comment by Bougagi** [comment]
I start chromedriver with the command "chromedriver --port=4444" mentioned in the Getting Started section.  I have no error.

**Comment by Bougagi** [comment]
> > Also, make sure you use compatible Chrome / Chromedriver version
> 
> 

Chromedriver is for chrome 83 so it should be ok. Maybe it is because i'm using chromium instead of google chrome ?

**Comment by Bougagi** [comment]
I installed google chrome and the issue is still here.

**Comment by Bougagi** [comment]
I just tried with firefox and gecko driver and it's working fine.
Seems to be chrome issue. You were using chrome when it worked for you ?

**Comment by Bougagi** [comment]
Hey @OndraM , just realized that i need to use chrome beacause i need to open multiple RemoteWebDriver and i haven't found a way to do it with firefow and gecko driver. I'm kind of stuck with the chrome issue. I tried with the latest chrome beta with chromedriver associated but still the whitespace and 6 issue...

**Comment by andrewnicols** [comment]
Using Chrome 83 and Selenium, I’m unable to reproduce this issue.

I’ll try tomorrow using Chromedriver directly.

**Comment by Bougagi** [comment]
Hi thanks for your reply. What do you mean by testing directly on chromedriver ?

**Comment by andrewnicols** [comment]
I tested this evening using Selenium Server which loads ChromeDriver. It is also possible to run ChromeDriver without Selenium.

**Comment by Bougagi** [comment]
Yeah i tried with selenium server, same issue... I don't know what to do...

**Comment by Bougagi** [comment]
Hi, i tried with selenium javascript and i also have this issue with chrome so it is on my side i guess... What could possibly cause this ?

**Comment by Bougagi** [comment]
@OndraM @andrewnicols Can the sendKeys method be affected by the region ? Because i realized that for unknown reason, the google results are in spanish and google locates me in peru. Maybe the sendkeys method sends the good information but the keyboard language changes some keys like 6 and space in my case. Is there an option to force google region in the chromedriver options ? 

Thanks for your time, i'm desperate...

**Comment by andrewnicols** [comment]
Hi @Bougagi, Not that I can think of.

Could you provide an entire PHP testcase with details of the ChromeDriver version you're using. I've been unable to reproduce this at all.

**Comment by tototoshi** [comment]
I too encountered this strange problem.
I found out two things.

- The problem does not occur on Mac, but it does on Linux (Debian 11 with Docker)
- It is important that it is '6'. '7' does not cause the problem.

I used ChromeDriver 103.0.5060.53.

**Comment by tototoshi** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1509
This may be the cause. I was using tightvnc.
