### ISSUE TITLE
New Mink WebDriver

### ISSUE THREAD

**Issue by andrewnicols** [php-webdriver/php-webdriver#807]
Hi @OndraM ,

@oleg-andreyev and I have been working on a new Mink WebDriver which makes use of this project.

I've pinged you on https://github.com/oleg-andreyev/MinkPhpWebDriver/issues/4 but do you think it would be possible and/or make sense to relocate the project to /php-webdriver?

Cheers

**Comment by OndraM** [comment]
Sorry, replied in the original issue.
