### ISSUE TITLE
Child process takes screenshots error

### ISSUE THREAD

**Issue by nachitox** [php-webdriver/php-webdriver#808]
### What are you trying to achieve? (Expected behavior)

I read [this article](https://dev.to/liviufromendtest/video-recording-for-selenium-webdriver-530e) and thought it would be a good idea to automate screenshot taking.
So, I want to take screenshots every 200ms to generate a video of the test by forking the process and making the child to take screenshots while the parents keeps with the test.

### What do you get instead? (Actual behavior)

I get an error on the next parent driver call

```
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/4be3207bdf6f9badb5646348d2844ebb/element with params: {"using":"css selector","value":"#review\\5F submit\\5F button"}

Operation timed out after 119635 milliseconds with 191892 out of 355648 bytes received
```

### How could the issue be reproduced? (Steps to reproduce)

I run the standalone server:

```
/usr/bin/java -Dwebdriver.chrome.driver="PATH_TO_chromedriver" -Dwebdriver.gecko.driver="PATH_TO_geckodriver" -jar PATH_TO_selenium-server-standalone-3.9.1.jar
```

Then call the test which sets the driver and try to fork the process so the child takes screenshots ever 200ms

```php

		$options = (new ChromeOptions)->addArguments([
			'--disable-gpu',
			'--ignore-certificate-errors',
			'--headless',
			'--window-size=1920,1440',
			'--disable-dev-shm-usage',
			'--no-sandbox'
		]);

		$desiredCapabilities->setCapability(ChromeOptions::CAPABILITY, $options);
		$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $desiredCapabilities, 120 * 1000, 120 * 1000);

		$driver->get(URL, true));

		// Take screenshots
		$pid = pcntl_fork();
		if ($pid == -1)
		{
			$childPid = NULL; // no screenshots
		}
		elseif ($pid)
		{
			$childPid = $pid; // we are the parent keep working
		}
		else
		{
			// we are the child
			$i = 1;
			while (1)
			{
				$driver->takeScreenshot(TESTS . 'screenshots/pic' . str_pad($i, 4, 0, STR_PAD_LEFT) . '.png');
				$i++;

				// wait for 0.2 seconds
				usleep(200000);
			}
		}

		// wait for page load
		$driver->wait()->until(
			WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('review_submit_button'))
		);
```

Is there any problem with my approach? Someone knows what is wrong?
Thanks

### Details

* Php-webdriver version: 1.8.2
* PHP version: 7.0.33
* Selenium server version: 3.9.1
* Operating system: Ubuntu 16
* Browser used + version: Google Chrome 83.0.4103.106

**Comment by OndraM** [comment]
I would not bet all code is thread safe, so my first guess would be some issue with parallelism.

You may try this with chromedriver running on its own, ie. without selenium server. Also have look at the output of selenium server (`-debug`) or chromedriver (`--log-level=ALL`).

**Comment by OndraM** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action.

If the original issue author adds comment with more information, we can reopen it and we can investigate further.
