### ISSUE TITLE
lack of documentation with full code

### ISSUE THREAD

**Issue by amidevous** [php-webdriver/php-webdriver#809]
your documentation is imcphréssible gibberish compared to curl

lack of example with full code

didn't even get the code for a page

the only thing we can do is get the title of the page from google

put that we are just trying to get the one from the page we really want

have this found with chrome which remains open

and a blank page on the browser making the request (firefox)

please help me

    require_once('vendor/autoload.php');

    use Facebook\WebDriver\Remote\RemoteWebDriver;

    use Facebook\WebDriver\WebDriverBy;

    $web_driver = RemoteWebDriver::create(

    "http://localhost:4444/wd/hub",

    array("platform"=>"LINUX", "browserName"=>"chrome", "version" => "latest", "name" => "First Test",), 12000000

    );

   $web_driver->get("https://tirexo.pro");

   $title = $web_driver->getTitle();

   $web_driver->quit();

   echo $title;

I have the impression that the fact that the browser returns a blank page and has a timeout which is not even provided

it's simple its must be like curl

if there is no timeout provided by the user there should be no

So to start how to remove this timeout which is totally unnecessary

and 2 how to get the source code of the page and not the title

this code is not even provided on your doc I had to find it elsewhere

it's not complicated to give more example

same php gives examples of execution of curl which works

thank you in advance

**Comment by amidevous** [comment]
ok I found it but it really lacks code example your thing not to complicate to put his example




    require_once('vendor/autoload.php');


    use Facebook\WebDriver\Remote\RemoteWebDriver;


    use Facebook\WebDriver\WebDriverBy;



    $web_driver = RemoteWebDriver::create(


    "http://localhost:4444/wd/hub",


    array("platform"=>"LINUX", "browserName"=>"chrome", "version" => "latest", "name" => "First Test",), 600000, 600000);


    $web_driver->get("https://google.com");


    $page = $web_driver->getPageSource(); 


    $web_driver->quit();


    echo $page;

**Comment by OndraM** [comment]
Hi,
this is an open-source community-driven project, maintained in our free time. You are more then welcome to contribute with more comprehensive documentation.

If you have an issue, please create a new one and fill the template provided when creating issue.
