### ISSUE TITLE
Firefox 80 incompatibility issue 'Expected "handle" to be a string, got [object Undefined] undefined'

### ISSUE THREAD

**Issue by AL-Kateb** [php-webdriver/php-webdriver#817]
### What are you trying to achieve? (Expected behavior)
When trying to switch to a new window, in previous windows I always got the window handle from getWindowHandles(), and then passed the one I need to switchTo()->window($handle), yesterday my firefox was automatically updated to version 80, and a my script started throwing the following exception:
`Facebook\WebDriver\Exception\InvalidArgumentException: Expected "handle" to be a string, got [object Undefined] undefined in webdriver/lib/Exception/WebDriverException.php:99
Stack trace:
#0 webdriver/lib/Remote/HttpCommandExecutor.php(370): Facebook\WebDriver\Exception\WebDriverException::throwException('invalid argumen...', 'Expected "handl...', Array)
#1 webdriver/lib/Remote/RemoteWebDriver.php(590): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 webdriver/lib/Remote/RemoteExecuteMethod.php(27): Facebook\WebDriver\Remote\RemoteWebDriver->execute('switchToWindow', Array)
#3 webdriver/lib/Remote/RemoteTargetLocator.php(114): Facebook\WebDriver\Remote\RemoteExecuteMethod->execute('switchToWindow', Array)
#4 /var/www/html/execute.php(175): Facebook\WebDriver\Remote\RemoteTargetLocator->window('2147483652')
#5 {main}`

### How could the issue be reproduced? (Steps to reproduce)
Using switchTo()->window() on Firefox 80 and latest version of php-webdriver, will most likely reproduce this issue.

The code I use is:
````    
    $windowHandlesBefore = $driver->getWindowHandles();

    $btn->click();

    $windowHandlesAfter = $driver->getWindowHandles();

    $handles = $windowHandlesAfter;

    $newWindowHandle = array_diff($windowHandlesAfter, $windowHandlesBefore);

    $newWindow = reset($newWindowHandle);

    $driver->switchTo()->window($newWindow);
````

I traced the $newWindow variable from this point right to the point where the issue is thrown: the encoded_param does in fact has "handle" as name and the window handle number as the value, so the issue isn't in the code, which was working recently just before updating to Firefox 80

### Details

* Php-webdriver version: latest, pulled from rep just now
* PHP version: 7.2.24
* Selenium server version: 3.141.59
* Operating system: Ubuntu 18.04.3
* Browser used + version: Firefox 80 + Geckodriver 0.27.0

When I downgraded to firefox 79.0, this issue disappeared.

Is this a firefox bug?

Thanks

**Comment by OndraM** [comment]
Could you please provide the PHP code snippet you use for switching window?

Also, what is the version of geckoriver you use?

**Comment by AL-Kateb** [comment]
> Could you please provide the PHP code snippet you use for switching window?
> 
> Also, what is the version of geckoriver you use?

I updated the post, the PHP code most likely has no issues, because it was working fine yesterday, what triggered this issue is the automatic update of firefox to version 80

**Comment by alexanderkranga** [comment]
I started to get the same issue as @AL-Kateb . We have tests that are executed on Saucelabs, and I am using latest version of Firefox. On 25th of August Firefox version was 79 and it was running fine, but it started to fail recently with the same error:
```
org.openqa.selenium.InvalidArgumentException: Expected "handle" to be a string, got [object Undefined] undefined
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '***', ip: '***', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.108', java.version: '1.8.0_222'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 80.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200818235255, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 5568, moz:profile: C:\Users\sauce\AppData\Loca..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, selenium:webdriver.remote.quietExceptions: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: d4fb8e41-8aa5-4635-8217-a0d...}
```

And it fails on the same step - when trying to get window handle. Code example:
```String windowHandle = driver.getWindowHandle();```

I strongly believe it is a bug with Firefox

**Comment by OndraM** [comment]
Yes, this looks like in issue not related to php-webdriver, I found also report of the same error with Python bindings: https://github.com/SeleniumHQ/selenium/issues/8649 

However I can't find issue addressing this directly in [geckodriver](https://github.com/mozilla/geckodriver/issues) (there are some other issues related to window handling, though). 

As this bug seems to be out of scope of php-webdriver, I kindly ask you to report it directly to geckodriver issue tracker.

**Comment by ozerkon** [comment]
I faced the same issue today morning. 

Details
 
- Language : c#
- Selenium server version: 3.141.0
- Operating system: Windows 10
- Browser : Firefox 80 (Newly upgraded)
- Gecko version : 0.26

The issue was resolved when the GeckoDriver upgraded from 026 to 0.27.

**Comment by stefanocorsi** [comment]
Language: Rails 6.0.3.2
capybara (3.32.2)
selenium: selenium-webdriver (3.142.7)
Browser: 80.0.1 (64-bit) on windows 10

Confirm resolution when upgrading geckodriver to 0.27.0. Thanks @ozerkon

**Comment by johnnavarra** [comment]
This still seems to be an issue
Details

Language : c#
Selenium server version: 3.141.0
Operating system: Windows 10
Browser : Firefox 81 (Newly upgraded)
Gecko version : 0.27

**Comment by OndraM** [comment]
@johnnavarra Please note this issue tracker is for PHP library only, not for C#. 

If anyone is facing the error, have a look to the error logs and make *definitely* sure you are using Geckodriver 0.27.0. From the reports in upstream issue (https://github.com/SeleniumHQ/selenium/issues/8649) so far everyone with this issue was in fact using old geckodriver.
