### ISSUE TITLE
Testing Problems | no DISPLAY enviroment variable specified | JavaScript error: NS_ERROR_FAILURE: Should pass a non-null uri

### ISSUE THREAD

**Issue by jackchevalley** [php-webdriver/php-webdriver#822]
**Classes:** Selenium PHP / Steward
**Jar:** selenium-server-standalone-4.0.0-alpha-2.jar
**Driver:** GeckoDriver -> firefox 
**Browser:** Firefox
**Os:** Ubuntu 18

I followed the instruction to install Steward, Selenium, Firefox, Java ec..
I created the test file that is asks with their code: 

```php
<?php
// selenium-tests/tests/TitlePageTest.php

namespace My; // Note the "My" namespace maps to the "tests" folder, as defined in the autoload part of `composer.json`.

use Facebook\WebDriver\WebDriverBy;
use Lmc\Steward\Test\AbstractTestCase;

class TitlePageTest extends AbstractTestCase
{

	public function testShouldContainSearchInput()
	{
		// Load the URL (will wait until page is loaded)
		$this->wd->get('http://www.w3.org/'); // $this->wd holds instance of \RemoteWebDriver

		// Do some assertion
		$this->assertContains('W3C', $this->wd->getTitle());

		// You can use $this->log(), $this->warn() or $this->debug() with sprintf-like syntax
		$this->log('Current page "%s" has title "%s"', $this->wd->getCurrentURL(), $this->wd->getTitle());

		// Make sure search input is present
		$searchInput = $this->wd->findElement(WebDriverBy::id('search-submit'));
		// Or you can use syntax sugar provided by Steward (this is equivalent of previous line)
		// $searchInput = $this->findByCss('#search-form input');

		// Assert title of the search input
		$this->assertEquals('Search', $searchInput->getAttribute('title'));
	}
}

?>
```

The code connect to localhost:4444 (where selenium-server-standalone in listening) and both connect to each other.
As soon as it connect it throws an error: __Error: no DISPLAY environment variable specified__
I checked wich display where able to use doing: (this command was found on google while attempting to fix)
```
xauth list|grep 'uname -n'     
Print: XXXXXX/unix:0  MIT-MAGIC-COOKIE-1  aab0f605987c2yy8af471bb1ec1f8a69
```
So i set environment variable to :0 
```
export DISPLAY=:0
```
Tring to restart the code it always throws the same error but doing  `echo $DISPLAY` in ssh it print :0 that is what I set
So I installed a program (ephemeral-x.sh) that allows me to run selenium-server without a display.
The error that I had before does not display but there is a new one.
```
JavaScript error: resource://gre/modules/URIFixup.jsm, line 271: NS_ERROR_FAILURE: Should pass a non-null uri
```
Looking on google since 2 hours I didn't find anything that was useful for my problem, anyone have an idea of how to solve it?
I can decide if selenium has to run with or without display so if u have an idea for the first problem or the second one, we can try both.
I just need it to work :(
If u need more infos just ask. Tks to everyone

**Comment by andrewnicols** [comment]
It sounds like you’re trying to run the browser from a headless terminal session. That could be a testing environment, or an ssh session, etc.

I’d recommend trying a suitable Docker image, or xvfb, or running the browser headless.

**Comment by jackchevalley** [comment]
> It sounds like you’re trying to run the browser from a headless terminal session. That could be a testing environment, or an ssh session, etc. I’d recommend trying a suitable Docker image, or xvfb, or running the browser headless.

I fixed everything removing firefox and selenium-server and running on chromedriver and chrome-stable
