### ISSUE TITLE
Attribute innerText/innerHTML is empty (Geckodriver)

### ISSUE THREAD

**Issue by mraspe** [php-webdriver/php-webdriver#825]
### What are you trying to achieve? (Expected behavior)
Attribute "innerText/innerHTML" of an element (td) should not be empty (in Firefox).

### What do you get instead? (Actual behavior)
In Chrome I get the correct string of an element attribute (innerText). In Firefox the string is always empty.

### How could the issue be reproduced? (Steps to reproduce)
In a PHP test I try to get the content of an element (td):  $column->getAttribute('innerText');
With Selenium server version 3.8.1 it had still worked. With version 3.141.59 it only works in chrome.

### Details
* Php-webdriver version: 1.8.3
* PHP version: 7.2.34
* Selenium server version: 3.141.59
* Operating system: Win10
* Browser used + version: Firefox 81.0, Chrome 85.0.4183.121
* Geckodriver: 0.27.0
* Chrome Diver: 85.0.4183.38

**Comment by OndraM** [comment]
Hi, what is the use-case for this?

You can use native WebDriver methods `$element->getText()` to get text value.

And `getAttribute()` is used to get value of DOM element attribute (like "class", "id", "style" etc.) . And `innerText` nor `innerHTML` are DOM attributes, they are DOM properties. To get their value, I suggest using executeScript and access the value via JavaScript, something like:

```php
$innerHtml = $driver->executeScript('return arguments[0].innerHtml', $element)
```

**Comment by mraspe** [comment]
Hi,
okay, thank you!

I was wondering why you get different values with "innerText" (empty, not empty) in Chrome and Firefox. With $element->getText it works,

**Comment by OndraM** [comment]
Glad to help!

Chromedriver have many non-standard features, so this may be why it works. But I would not rely on it.

Geckodriver tends to stick more with the WebDriver [W3C standard](https://w3c.github.io/webdriver/), and it does not specify such behavior, so this is why it doesn't work.
