### ISSUE TITLE
AntiCaptcha Equivalent for acp_api_send_request

### ISSUE THREAD

**Issue by grekpg** [php-webdriver/php-webdriver#834]
Hi i try use AntiCaptcha plugin https://antcpt.com/eng/how-to-use.html

i python i need 

browser.get('https://antcpt.com/blank.html')
# Install the anti-captcha.com API key
# replace YOUR-ANTI-CAPTCHA-API-KEY with your hexadecimal key that you can get here:
# https://anti-captcha.com/clients/settings/apisetup
acp_api_send_request(
    browser,
    'setOptions',
    {'options': {'antiCaptchaApiKey': 'MYKEY'}}
)

in php i 

 $this->webDriver->get('https://antcpt.com/blank.html');

and how send browser options ?

**Comment by OndraM** [comment]
Hi, sorry, I don't think this is related to php-webdriver.

However, anyone willing to help could do so in you StackOverflow question: https://stackoverflow.com/questions/64966981/php-webdriver-anticaptcha-equivalent-for-acp-api-send-request

**Comment by grekpg** [comment]
Ok but i think is related to php-webdriver. - This is chrome plugin set parameter. It should by possible to set if from python is possible ?

**Comment by RestOp** [comment]
> Ok but i think is related to php-webdriver. - This is chrome plugin set parameter. It should by possible to set if from python is possible ?

Have you figured out how to do it?
