### ISSUE TITLE
How to keep selenium alive and detect if session has been expired?

### ISSUE THREAD

**Issue by plonknimbuzz** [php-webdriver/php-webdriver#839]
### Q1: Is possible to keep selenium alive (long live)?
Currently im using 
`java -Dwebdriver.chrome.driver="/var/selenium/chromedriver" -jar /var/selenium/selenium.jar  -timeout 86400`
i expected like `-timeout 0` or `-timeout -1`
i know this will be bad because will cause leak memory. But i just need to know if this possible or not?

### Q2: How to detect if session has been expired?
**Expected:**
i can handle the exception using `InvalidSessionIdException`

**Current condition:**
Fatal error because cannot catch the exception, and i didn't find `InvalidSessionIdException` on [documentation](https://php-webdriver.github.io/php-webdriver/latest/)

**How to reproduce:**
i run: `php a.php obama aaaaa` => aaaa is invalid /expired sessionid
```
php a.php selenium aaaaaa
continue session 
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\InvalidSessionIdException: invalid session id in /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:107
Stack trace:
#0 /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(370): Facebook\WebDriver\Exception\WebDriverException::throwException()
#1 /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(589): Facebook\WebDriver\Remote\HttpCommandExecutor->execute()
#2 /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(213): Facebook\WebDriver\Remote\RemoteWebDriver->execute()
#3 /var/www/html/sampah/selenium/a.php(76): Facebook\WebDriver\Remote\RemoteWebDriver->findElement()
#4 {main}
  thrown in /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php on line 107

Fatal error: Uncaught Facebook\WebDriver\Exception\InvalidSessionIdException: invalid session id in /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:107
Stack trace:
#0 /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(370): Facebook\WebDriver\Exception\WebDriverException::throwException()
#1 /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(589): Facebook\WebDriver\Remote\HttpCommandExecutor->execute()
#2 /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(213): Facebook\WebDriver\Remote\RemoteWebDriver->execute()
#3 /var/www/html/sampah/selenium/a.php(76): Facebook\WebDriver\Remote\RemoteWebDriver->findElement()
#4 {main}
  thrown in /var/www/html/sampah/selenium/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php on line 107
```

usage: `php a.php [keywordToSearch] [sessionID]`
this script is just for demo purpose
```php
<?php 
namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\WebDriverCapabilityType;
use Facebook\WebDriver\Remote\LocalFileDetector;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverExpectedCondition;
use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\WebDriverKeys;
use Facebook\WebDriver\Exception\ExpectedException;
use Facebook\WebDriver\Exception\WebDriverCurlException;
use Facebook\WebDriver\Exception\NoSuchElementException;
use Facebook\WebDriver\Exception\TimeOutException;
use Facebook\WebDriver\Exception\InvalidSessionIdException;
use Facebook\WebDriver\Exception\SessionNotCreatedException;
use Facebook\WebDriver\WebDriverWindow;
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

/*
	USAGE : php test.php [keyword] [sessionID] 

*/
$search = isset($argv[1])?$argv[1]:null;
$id = isset($argv[2])?$argv[2]:null;

if(!$search){
	echo 'Keyword is required'.PHP_EOL;
	exit;
}

require_once('vendor/autoload.php');

$options = new ChromeOptions();
$options->addArguments(array(
	'no-sandbox',
	'disable-infobars',
	'disable-gpu',
	//'headless',
));

$options->setExperimentalOption('excludeSwitches', ['enable-automation']);
$host = 'http://localhost:4444';
//$host = 'http://localhost:4444/wd/hub'; 
$capabilities = DesiredCapabilities::chrome();
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

//start here
if($id){
	echo 'continue session '.PHP_EOL;
	try{
		$driver = RemoteWebDriver::createBySessionID($id,$host);
	}catch(InvalidSessionIdException $e){
		/*
			This not triggered when sessionId not found/invalid
		*/
		echo 'continue session failed '.PHP_EOL;
		$driver = RemoteWebDriver::create($host, $capabilities, 5000);
		$driver->get('http://www.wikipedia.org/');
	}catch(SessionNotCreatedException $e){echo 1;exit;
		/*
			This not triggered when sessionId not found/invalid
		*/
		echo 'continue session failed '.PHP_EOL;
		$driver = RemoteWebDriver::create($host, $capabilities, 5000);
		$driver->get('http://www.wikipedia.org/');
	}
}else{
	echo 'create session '.PHP_EOL;
	$driver = RemoteWebDriver::create($host, $capabilities, 5000);
	$driver->get('http://www.wikipedia.org/');
}

$driver->findElement(WebDriverBy::id('searchInput'))->sendKeys($search)->submit();

$id = $driver->getSessionID();
echo 'id: '.$id.PHP_EOL;

//no $driver->quit() because i will let this browser open for future purpose
```

**Browser:** Chromedriver 86
**OS:** Ubuntu 18
**phpwebdriver:** 1.8
**PHP**: 7.4

**Comment by andrewnicols** [comment]
> Q1: Is possible to keep selenium alive (long live)?
> Currently im using
> java -Dwebdriver.chrome.driver="/var/selenium/chromedriver" -jar /var/selenium/selenium.jar -timeout 86400
> i expected like -timeout 0 or -timeout -1
> i know this will be bad because will cause leak memory. But i just need to know if this possible or not?

Selenium will keep running until you kill it (ctrl-c, etc).
The `timeout` parameter is unrelated and is the value used for waiting for a response between Selenium and the driver for each browser (i.e. Chromedriver).

> Q2: How to detect if session has been expired?
The way you're doing it will work, but the stacktrace points to line 76, which is the `findElement` call which is outside of the try/catch.

Generally speaking it's more typical to have a script create the session, perform all work, and then end the session - i.e. all in the same PHP Process. It is unusual to start a session in one process, and then have a separate process use the same session which is what you seem to be doing by echoing the ID and then passing it in as a CLI argument the next time you call the script. Yes, it is possible, but it's also a little bit dirty.

**Comment by plonknimbuzz** [comment]
thanks for the reply @andrewnicols 

Q1: my bad. i just forgot it. thanks for remembering me

Q2: check if selenium session still exists
1. i'm not notice about multiple process in 1 browser. i just notice about checking if selenium session still valid or not
2. even my code in findElement is not work. but my problem is always i got error on `InvalidSessionIdException` because i l'm not able to catch it

i will make simple question for Q2:
**how to catch error if sessionId is not valid?**
