### ISSUE TITLE
Request timeout can be shorter than page timeout

### ISSUE THREAD

**Issue by andrewnicols** [php-webdriver/php-webdriver#859]
### Bug description
We have a couple of places where we have some very long requests. These are well below the 300 second `pageLoad` timeout (https://www.w3.org/TR/webdriver/#timeouts), but the CURL_TIMEOUT default value is 30 seconds.

That means that the request timesout.

### How could the issue be reproduced

1. Create two pages:
1. * a page with a 35 second sleep
1. * a page which links to that page
2. Navigate to the link page
3. Click on the link
4. Wait

### Expected behavior
The request completes

### Actual behaviour
We get a curl timeout

### Details

* Php-webdriver version: master
* PHP version: 7.4
* How do you start the browser: Selenium / Chromedriver
* Selenium server version: 4.0.0alpha
* Operating system: MacOS
* Browser used + version: Chrome 88.0.4324.96
* Browser driver chromedriver version: 88.0.4324.96

**Comment by andrewnicols** [comment]
We shoudl probably respect the respective timeout. The default timeouts are:
* script: 30,000 ms
* pageLoad: 300,000 ms
* implicit: 0 ms

https://www.w3.org/TR/webdriver/#timeouts

We should use the script timeout (30 seconds) for the {{execute/*}} endpoints
We should use the implicit timeout (unest) for the {{/element}} and {{/elements}} endpoints
We should use the pageLoad timeout (300 second) for all other endpoints

The timeouts are usually returned in the returned capabilities, but that isn't guaranteed. In that instance we can fetch the timeouts using the /timeouts endpoint to fetch the timeouts.

That isn't supported at all on JsonWire so we'll just have to go with the existing behaviour and/or the defaults.

**Comment by OndraM** [comment]
So what do you suggest from implementation point of view? Increase the current  30 second curl request timeout in `HttpCommandExecutor` to make it consistent with the default pageLoad timeout?

Because the CURL request timeout determines what is the maximum time the request can take. From what I understand, if you do `get()` to some webpage, and it takes longer then 30 seconds, you will get Curl error, even if you pageLoad timeout is set to 300 seconds, right?

**Comment by oleg-andreyev** [comment]
> some webpage, and loading the page takes longer then 30 seconds, you will get Curl error, even if you pageLoad timeout is set to 300 seconds, right?

Right. But I think that 300s for page load is too long...
