### ISSUE TITLE
Ad blocker enabled

### ISSUE THREAD

**Issue by kenygamer** [php-webdriver/php-webdriver#882]
### Bug description
I am having an issue when trying to fetch data from some sites, e.g `courir.com`. When I try to send a request with php-webdriver, an alert pops up saying:

Please enable JS or disable any ad blocker.

I was very inquisitive before opening this issue, and I have been able to verify that this issue replicates on other sites as well, for instance, `target.com`.

Upon inspecting the code, in a search, the web page loads with the following content:

However when I try in a normal browser, I get this web page:

When I go to the front page, the page loads successfully:

Which makes me highly doubt that it is an Ad blocker, or JavaScript in the last case. However, I have been able to parse Javascript powered webpages successfully in the past.

### How could the issue be reproduced

```php
$serverUrl = "http://localhost:4444/";
$desiredCapabilities = DesiredCapabilities::chrome();
$driver = RemoteWebDriver::create($serverUrl,
$desiredCapabilities);
$driver->get("https://www.target.com/s?searchTerm=towel");
print_r($driver->getPageSource()); //Error
```

### Details

* Php-webdriver version: 1.10.0
* PHP version: 8.0.0
* How do you start the browser: Chromedriver
* Selenium server version: N/A
* Operating system: Ubuntu 20.04.2 LTS
* Browser used + version: chromium-browser:amd64/bionic-security 87.0.4280.66-0ubuntu0.18.04.1 uptodate
* Browser driver (chromedriver/geckodriver...) version: ChromeDriver 89.0.4389.90

**Comment by OndraM** [comment]
This does not seem like a bug - I tested the code and it works completely fine.

> Browser used + version: chromium-browser:amd64/bionic-security 87.0.4280.66-0ubuntu0.18.04.1 uptodate
> Browser driver (chromedriver/geckodriver...) version: chromium 89.0.4389.90

Please note *you MUST* use the compatible ( = same) versions of chromium and chromedriver. It seems you have version 87 of chromium but 89 of chromedriver, ant this may cause the issues.

Also a side note - when reporting an issue, please provide the full error you get. `print_r($driver->getPageSource()); //Error` won't help, as it is missing the exact error you get.

**Comment by kenygamer** [comment]
> This does not seem like a bug - I tested the code and it works completely fine.
> 
> > Browser used + version: chromium-browser:amd64/bionic-security 87.0.4280.66-0ubuntu0.18.04.1 uptodate
> > Browser driver (chromedriver/geckodriver...) version: chromium 89.0.4389.90
> 
> Please note _you MUST_ use the compatible ( = same) versions of chromium and chromedriver. It seems you have version 87 of chromium but 89 of chromedriver, ant this may cause the issues.
> 
> Also a side note - when reporting an issue, please provide the full error you get. `print_r($driver->getPageSource()); //Error` won't help, as it is missing the exact error you get.

Sorry for the lack of specificity, I am not having any PHP or php-webdriver error, the issue is the empty page that I described in my issue:

![](https://i.ibb.co/pwN4xct/0978-BB8-D-4-C1-E-400-B-8744-68-E706-E48-A38.png)

However, when I go to a normal browser, I get this page:

![](https://i.ibb.co/wQNTPMd/87-DC6773-1-A56-4-BBE-A79-C-4-C8694-BA7468.jpg)

**Comment by kenygamer** [comment]
@OndraM

**Comment by kenygamer** [comment]
@OndraM
