### ISSUE TITLE
Screenshot of clicked select box shows displaced options

### ISSUE THREAD

**Issue by alexander-nitsche** [php-webdriver/php-webdriver#905]
### Bug description
I use the `php-webdriver` package to do extensive screenshots of my application. All screenshots looked as expected, but there occurred one phenomenon: When clicking a form select box and taking a screenshot, the options do not get rendered below the select box but rendered with some distance. It is always the same distance, no matter if in a simple HTML file with only the select box, or in a complex CMS backend with Bootstrap loaded.

### How could the issue be reproduced

1. Run selenium grid-3 or grid-4 server with chrome driver, e.g. by
    ```
    docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-beta-3-20210426
    ```
2. Create an HTML file at a web server, e.g. `http://localhost/test.html`
    ```html
    <html>
    <body>
        <form>
            <select>
                <option>Option 1</option>
                <option>Option 2</option>
            </select>
        </form>
    </body>
    </html>
    ```
3. Create the PHP file at the web server, , e.g. `http://localhost/run.php`
    ```php
    <?php
    require '/var/www/html/vendor/autoload.php';

    use Facebook\WebDriver\Chrome\ChromeOptions;
    use Facebook\WebDriver\Remote\DesiredCapabilities;
    use Facebook\WebDriver\Remote\RemoteWebDriver;
    use Facebook\WebDriver\WebDriverBy;

    $serverUrl = 'http://localhost:4444/wd/hub';

    // Chrome
    $driver = RemoteWebDriver::create($serverUrl, DesiredCapabilities::chrome());
    $driver->get('http://localhost/test.html');
    $driver->takeScreenshot('selectbox_closed.png');
    $driver->findElement(WebDriverBy::tagName('select'))->click();
    $driver->takeScreenshot('selectbox_open.png');
    $driver->quit();

    ```
4. Run the PHP file and check the resulting screenshot: It should look like this:
    ![selectbox_open](https://user-images.githubusercontent.com/20297232/117993481-1239f880-b340-11eb-935f-c0681a307d65.png)

### Expected behavior
The options should be rendered exactly below the select box.

### Details
* Php-webdriver version: 1.10.0
* PHP version:  7.4.15
* How do you start the browser driver or Selenium server:
  ```
  docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-beta-3-20210426
  ```
* Selenium server version: Selenium Grid-4 4.0.0-beta-3
* Browser driver version: ChromeDriver 90.0.4430.24
* Browser used + version: Google Chrome 90.0.4430.85
* Operating system: Debian Buster

**Comment by OndraM** [comment]
Hi, thanks for the report. I can confirm this behavior on chromedriver, even when run without docker and without selenium server (ie. directly using `chromedriver` binary).

From my tests, this does not happen when running chrome [in headless mode](https://github.com/php-webdriver/php-webdriver/wiki/Chrome#start-chrome-in-headless-mode) - the dropdown is then rendered correctly.

From this signs it doesn't seem like anything which php-webdriver can affect. My guess is it is rather some rendering issue in chromedriver. I suggest [reporting it to chromedriver team](https://bugs.chromium.org/p/chromedriver/issues/list).

**Comment by alexander-nitsche** [comment]
> From my tests, this does not happen when running chrome in headless mode - the dropdown is then rendered correctly.

What a side note! Thanks, this solved the issue.

**Comment by alexander-nitsche** [comment]
Reported the issue to the chromedriver team here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3801 .
