### ISSUE TITLE
cannot set up chromeoptions setBinary

### ISSUE THREAD

**Issue by sir-reynolds** [php-webdriver/php-webdriver#906]
### Bug description
i have 2 chrome versions where one is installed and the other one i downloaded the zipped and unzipped version in my work folder.

Chrome browser installed version 90, and I extracted version 88. I have also provided version 88 chromedriver.

but when I set chromeoptions setbinary to chrome.exe version 88 and using chromedriver 88 it always raises an error because the library always reads chrome version 90 installed.

### How could the issue be reproduced

1. just start php cli and error

```php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Chrome\ChromeDriver;

require_once('vendor/autoload.php');

putenv( 'WEBDRIVER_CHROME_DRIVER=' . realpath( __DIR__ . '/tools/driver/chromedriver88.exe' ) );

$chromeOptions = new ChromeOptions();
$chromeOptions->setBinary( realpath( __DIR__ . '/tools/browser/chrome-win32/chrome88.exe' ) );

$driver = ChromeDriver::start();
$driver->get('https://en.wikipedia.org/wiki/Selenium_(software)');

sleep(5);

$driver->quit();
```

### Expected behavior
Can setup custom binary, not use installed browser.

### Details

* Php-webdriver version: 1.11.0
* PHP version:  7.2.19
* How do you start the browser driver or Selenium server: i don't know, i just use example code in php cli and add custom setbinary.
* Selenium server version: not used
* Browser driver (chromedriver/geckodriver...) version: chromedriver 88
* Browser used + version: chrome 88.0.4324.96
* Operating system: windows 10

### Additional context
```
λ php sample.php

DevTools listening on ws://127.0.0.1:49942/devtools/browser/8dca969a-d735-4fac-8454-14f652b4e9c8

Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 90.0.4430.212 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe in C:\laragon\www\php-webdriver\vendor\php-webdriver\webdriver\lib\Exception\WebDriverException.php:125
Stack trace:
#0 C:\laragon\www\php-webdriver\vendor\php-webdriver\webdriver\lib\Remote\HttpCommandExecutor.php(371): Facebook\WebDriver\Exception\WebDriverException::throwException('session not cre...', 'session not cre...', Array)
#1 C:\laragon\www\php-webdriver\vendor\php-webdriver\webdriver\lib\Remote\Service\DriverCommandExecutor.php(42): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 C:\laragon\www\php-webdriver\vendor\php-webdriver\webdriver\lib\Chrome\ChromeDriver.php(62): Facebook\WebDriver\Remote\Service\DriverCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDrive in C:\laragon\www\php-webdriver\vendor\php-webdriver\webdriver\lib\Remote\Service\DriverCommandExecutor.php on line 50
```

**Comment by OndraM** [comment]
Hi, it seems you are not passing `$chromeOptions` to the driver.

Try this:
```diff
$chromeOptions = new ChromeOptions();
$chromeOptions->setBinary( realpath( __DIR__ . '/tools/browser/chrome-win32/chrome88.exe' ) );

-$driver = ChromeDriver::start();
+$driver = ChromeDriver::start($chromeOptions);
```

**Comment by sir-reynolds** [comment]
> Hi, it seems you are not passing `$chromeOptions` to the driver as part of capabilities.
> 
> Try this:
> 
> ```diff
> $chromeOptions = new ChromeOptions();
> $chromeOptions->setBinary( realpath( __DIR__ . '/tools/browser/chrome-win32/chrome88.exe' ) );
> 
> +$capabilities = new DesiredCapabilities();
> +$capabilities->setCapability(ChromeOptions::CAPABILITY_W3C, $chromeOptions);
> 
> -$driver = ChromeDriver::start();
> +$driver = ChromeDriver::start($capabilities);
> ```

Thank you sir, this is work normally but i have some issue when run it.

`[9016:5448:0513/184706.766:ERROR:device_event_log_impl.cc(214)] [18:47:06.751] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)`

do you know about that and what should i do?

thank you very much, this is great framework.

**Comment by OndraM** [comment]
No, sorry, this seems like an issue unrelated to php-webdriver.
