### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by TKS-MateusMacedo** [php-webdriver/php-webdriver#954]
### Bug description

I need to config Proxy with User and Password, but didnt work.

### How could the issue be reproduced

1. Configure proxy with user and password
2.  Check if proxy is coneects
3. ...

```php
$proxyUrl = "http://$username:$password@zproxy.lum-superproxy.io:22225";
        
            $capabilities->setCapability(WebDriverCapabilityType::PROXY, [
                'httpProxy' => $proxyUrl,
                'sslProxy' => $proxyUrl,
                'ftpProxy' => $proxyUrl,
                "noProxy"   => "",
                'proxyType' => 'manual',
            ]);
```

### Expected behavior

Connect with Proxy

**Comment by mhbm** [comment]
I tried too and the proxy didn't work :(

**Comment by OndraM** [comment]
Hi, we have and an wiki page related to proxy configuration: https://github.com/php-webdriver/php-webdriver/wiki/HowTo-Work-with-proxy#proxy-with-authentication

In short: using proxy with authentication is not possible with either Chrome or Firefox, you can only use a workaround like `mitmproxy` - see the liked wiki for details.
