### ISSUE TITLE
RemoteWebElement::findElement() does not limit elements within the current element if xpath anywhere mechanism is used

### ISSUE THREAD

**Issue by stavinoj** [php-webdriver/php-webdriver#956]
### Bug description
`RemoteWebElement::findElement()` method does not limit elements within the current element if xpath mechanism with anywhere prefix '//' is used.

### How could the issue be reproduced

```php
$e = $driver->findElement(WebDriverBy::xpath('//div[@id="child"]'));
$e->findElement(WebDriverBy::xpath('//div[@id="parent"]'));
```

```html
<div id="parent">
  <div id="child"></div>
</div>
```

### Expected behavior
Throwing an exception. It returns the parent div instead.

* Php-webdriver version: 1.12.0
* PHP version:  7.3.33
* Selenium server version: 3.141.59
* Browser driver (chromedriver/geckodriver...) version: 96.0.4664.45 
* Operating system: Linux

**Comment by OndraM** [comment]
Hi, this is an expected behavior. `//` means in xPath root scope of the document, so it behaves as it should.

If you want to limit the scope from the relative element, add `.` on the beginning. 

```php
$e = $driver->findElement(WebDriverBy::xpath('//div[@id="child"]'));
$e->findElement(WebDriverBy::xpath('.//div[@id="parent"]'));
```

This will throw the expected `NoSuchElementExceptio`, as `parent` will not be found relative to `child` element.

**Comment by stavinoj** [comment]
Thanks for the xpath lesson but this was not the point of the bug report.

1. We are not talking about `RemoteWebDriver::findElement()` but about `RemoteWebElement::findElement()`  method whose documentation speaks quite clearly:

```php
    /**
     * Find the first WebDriverElement within this element using the given mechanism.
     *
     * @param WebDriverBy $by
     * @return RemoteWebElement NoSuchElementException is thrown in HttpCommandExecutor if no element is found.
     * @see WebDriverBy
     */
```

2. Also, with your logic the following code should not throw an `NoSuchElementException` exception but it actually DOES because it does not work with the root scope and properly limit the scope within the element:

```php
$e = $driver->findElement(WebDriverBy::cssSelector('div#child'));
$e->findElement(WebDriverBy::cssSelector('div#parent'));
```

Please either fix the bug or update the documentation because it is currently completely misleading.

**Comment by OndraM** [comment]
Hi,
I understand the confusion, but I still think this work as expected, this is just misunderstation of behavior of each locating strategy.

1) In XPath, `//` means "root scope of the whole document". Even when called on `RemoteWebElement`, by using `//` you are still explicitly specifying you want the selector the be applied on the root scope, and you don't want to work in the relative context. If you want the selector to apply relatively to the context node (which is what `RemoteWebElement` provides), use relative selector like `.//`. XPath is more powerful and you are in control whether you want to use the relative context or not. 

2) Css selectors mechanism behaves differently than XPath. There is no such selector to access parent elements (like `..` in XPath) or root scope (like `//`) in css selectors. It is just relative by default with no way to traverse the node tree.

This behavior is based on Selenium WebDriver implementation, it is not affected by php-webdriver library. See for example https://github.com/SeleniumHQ/selenium/issues/5501#issuecomment-366330464 .

But to avoid any further confusion, I extended the documentation, see #957.

**Comment by stavinoj** [comment]
Thanks a lot for updating the documentation.
