### ISSUE TITLE
Uncaught Error: Call to undefined function Facebook\WebDriver\Remote\curl_init()

### ISSUE THREAD

**Issue by iwasherefirst2** [php-webdriver/php-webdriver#965]
### Bug description
I try to run the example script but it fails with `PHP Fatal error:  Uncaught Error: Call to undefined function Facebook\WebDriver\Remote\curl_init() `

### How could the issue be reproduced

1. Install https://github.com/SeleniumHQ/docker-selenium and run container. Check if its running 
![image](https://user-images.githubusercontent.com/1765602/151932104-3378bfac-1200-40da-b3af-fc67dbb118e5.png)
2. Install this package using composer
3. Run php my-example-script

This is my-example-script

```php
<?php

// An example of using php-webdriver.
// Do not forget to run composer install before. You must also have Selenium server started and listening on port 4444.

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once('vendor/autoload.php');

// This is where Selenium server 2/3 listens by default. For Selenium 4, Chromedriver or Geckodriver, use http://localhost:4444/
$host = 'http://localhost:4444/wd/hub';

$capabilities = DesiredCapabilities::chrome();

$driver = RemoteWebDriver::create($host, $capabilities);

// navigate to Selenium page on Wikipedia
$driver->get('https://en.wikipedia.org/wiki/Selenium_(software)');

```

### Expected behavior
Actually I expect no output (not sure how to dump the body yet)

### Actual behavior:
```
adam@adam-Precision-3551:~/www/personal-projects/webdriver-test$ php request.php 
PHP Fatal error:  Uncaught Error: Call to undefined function Facebook\WebDriver\Remote\curl_init() in /home/adam/www/personal-projects/webdriver-test/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:125
Stack trace:
#0 /home/adam/www/personal-projects/webdriver-test/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(83): Facebook\WebDriver\Remote\HttpCommandExecutor->__construct()
#1 /home/adam/www/personal-projects/webdriver-test/request.php(18): Facebook\WebDriver\Remote\RemoteWebDriver::create()
#2 {main}
  thrown in /home/adam/www/personal-projects/webdriver-test/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php on line 125
```

### Details

* Php-webdriver version: 1.1.1
* PHP version:  8.0.11
* How do you start the browser driver or Selenium server:
   Using docker with $ docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:4.1.2-20220131
   and checked on localhost:4444
* Selenium server version: ?
* Browser driver (chromedriver/geckodriver...) version: Selenium Grid 4.1.2
* Browser used + version: no browser used
* Operating system:Ubuntu 18.04.6 LTS

**Comment by iwasherefirst2** [comment]
I didn't had curl module installed. Noticed it when using `php -m`. Had do install it like this: `sudo apt install php8.0-curl`

**Comment by ajmeese7** [comment]
I'm having this exact problem but I *do* have curl installed, it was installed with `php8.1-curl` and it is up to date. Any advice?
