### ISSUE TITLE
Failing to detect error response from Selenium

### ISSUE THREAD

**Issue by adam1010** [php-webdriver/php-webdriver#973]
### Bug description
If your code takes too long between sending commands to Selenium, then Selenium will time out. The next request you make to Selenium will fail, but this library is unable to detect that as an error and happily returns the payload as valid.

You can see that the `$results['error']` key is set, but we're only checking `$value['error']`. So we need to add another check that also looks at `$results['error']`

https://github.com/php-webdriver/php-webdriver/blob/main/lib/Remote/HttpCommandExecutor.php#L370

![image](https://user-images.githubusercontent.com/3019544/160501731-d95a62ff-daaa-40c8-903a-93101247f315.png)

Tested on the latest commit in `master`.  I'm using a recent Docker image for selenium `selenium/standalone-chrome:98.0-20220217`

**Comment by OndraM** [comment]
Hi @adam1010 ,
I tried to reproduce the issue, but I cannot find the problem.

Also according to [W3C WebDriver specification](https://w3c.github.io/webdriver/#errors), the errors should be encapsulated in `value['error']`. 

Could you please try in the latest Chrome version (104), and also provide the code you run where this error occurs?

Thanks a lot!
