### ISSUE TITLE
Some WebDriverKeys are not working

### ISSUE THREAD

**Issue by udhavsarvaiya** [php-webdriver/php-webdriver#976]
Using this I have successfully opened the Context menu
`$driver->getKeyboard()->sendKeys(array(WebDriverKeys::SHIFT, WebDriverKeys::F10));`

Open the Find Bar to search the current page is not working using this code
`$driver->getKeyboard()->sendKeys(array(WebDriverKeys::SHIFT, WebDriverKeys::F3));`

Here is just an example many keys are not working

I have windows 10 operating system, tested in chrome version 101.0.4951.41,

**Comment by OndraM** [comment]
Hi, it seems accessing Chrome search bar is not possible using Selenium. And it will be probably similar case for other browser features. The WebDriver is meant for interacting with the webpage itself, not with the browser user interface.
