### ISSUE TITLE
Missing % for base url

### ISSUE THREAD

**Issue by williamdes** [php-webdriver/php-webdriver#977]
https://github.com/php-webdriver/php-webdriver/blob/3a7a3c5801116f1b6cecf366a69e2750a384bde5/scripts/doctum.php#L29

See https://github.com/php-webdriver/php-webdriver/commit/05d690f8a60394b3d52c81fdaaca05b61957281e#diff-c6e0b804c4fd48a440a3d444a2dc591e9d3702d29c085c383c538f91de572714R34

**Comment by OndraM** [comment]
What is the issue here? The API docs seems to be working fine for all version.

Could you send a PR, please?

**Comment by williamdes** [comment]
> What is the issue here? The API docs seems to be working fine for all versions.
> 
> Could you send a PR, please?

If you look at https://github.com/php-webdriver/php-webdriver/commit/05d690f8a60394b3d52c81fdaaca05b61957281e#diff-c6e0b804c4fd48a440a3d444a2dc591e9d3702d29c085c383c538f91de572714R34 you will see the URL is broken
This is not noticeable for 99% of users but the opensearch URL will not work for Firefox users wanting to use it :)

> Could you send a PR, please?

Sure, here is #978

**Comment by williamdes** [comment]
Ref https://en.wikipedia.org/wiki/OpenSearch
