### ISSUE TITLE
Can not install it...

### ISSUE THREAD

**Issue by RestOp** [php-webdriver/php-webdriver#980]
Hello,

Trying to install it on Plesk and get an error from composer
![image](https://user-images.githubusercontent.com/46259141/172576569-a7bc668e-6245-431f-87dc-1093f3ce1649.png)

What am i doing wrong and please let me know how to fix it?

Thanks a lot!!!

**Comment by RestOp** [comment]
Seems that i need to add allow-plugins with any pugins inside (which?) somewhere (where in composer.json or?)

**Comment by williamdes** [comment]
> Seems that i need to add allow-plugins with any pugins inside (which?) somewhere (where in composer.json or?)

Here is an example: https://github.com/wdes/coding-standard#recommended-composerjson-config

But it may not work since you use probably the symfony phpcs fixer

**Comment by RestOp** [comment]
Thanks but which plugins do i have to allow?
