### ISSUE TITLE
createBySessionID() and getAllSessions() do not work anymore?

### ISSUE THREAD

**Issue by RestOp** [php-webdriver/php-webdriver#985]
Hello,

i am using 
Debain 10
Selenium-standalone-chrome:4.2.2-20220609 in docker.
I have googled a lot but still can not understand if it works or not or i have made a mistake...

**Q1: When i try to use createBySessionID() i get no action and no error even if i use unreal/random sessionID**

`<?php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;

require_once($cronPath . 'vendor/autoload.php');
$serverUrl = 'http://localhost:4444';
$id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$driver = RemoteWebDriver::createBySessionID($id, $serverUrl);
?>`

**Q2: When i try to use getAllSessions() i got**

`<b>Fatal error</b>:  Uncaught Facebook\WebDriver\Exception\UnknownCommandException: Unable to find handler for (GET) /sessions in /usr/share/nginx/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:137
Stack trace:
#0 /usr/share/nginx/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(372): Facebook\WebDriver\Exception\WebDriverException::throwException('unknown command', 'Unable to find ...', Array)
#1 /usr/share/nginx/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(572): Facebook\WebDriver\Remote\HttpCommandExecutor-&gt;execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /usr/share/nginx/html/test.php(58): Facebook\WebDriver\Remote\RemoteWebDriver::getAllSessions('http://localhost....')
#3 {main}
  thrown in <b>/usr/share/nginx/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php</b> on line <b>137</b><br />
`

my code is

`<?php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;

require_once($cronPath . 'vendor/autoload.php');
$serverUrl = 'http://localhost:4444';
$id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$driver = RemoteWebDriver::getAllSessions($serverUrl);
?>`

Thansk for help!

**Comment by OndraM** [comment]
Hi, when reporting an issue, please follow and fill the prepared template - otherwise we are missing key information and we are not able to provide help solving the issue. Thanks for your understanding.
